// Emit a TypeScript module of row / entity types from a SchemaContext.
//
// This is the compiler-native half of Kozou's type story (Kozou v0.2 spec
// §5.2): one `export interface` per table and view, describing the JSON row a
// client receives from @kozou/api. It is a pure function — no I/O — so the
// `kozou codegen` CLI (and tests) drive it directly.
//
// Scope: row / entity shapes only. The full API client surface (paths, query
// params, request/response envelopes, pagination, embeds) is better served by
// running an OpenAPI generator (e.g. openapi-typescript) against @kozou/api's
// `GET /openapi.json`, so this package does not reimplement that.

import type { SchemaContext, TableContext, ViewContext, ColumnContext } from '@kozou/core';
import { mapColumnType } from './mapType.js';

export type EmitOptions = {
  /** Emit the leading "generated by kozou" banner. Default: true. */
  header?: boolean;
};

const BANNER = [
  '// Generated by `kozou codegen` from PostgreSQL DDL + COMMENT. Do not edit by hand.',
  '//',
  '// Each interface is the JSON row shape returned by @kozou/api: `numeric` /',
  '// `bigint` are strings (node-postgres preserves precision), and temporal',
  '// columns are ISO strings. For the full API client surface, run an OpenAPI',
  "// generator against @kozou/api's `GET /openapi.json`.",
].join('\n');

export function emitRowTypes(schema: SchemaContext, opts: EmitOptions = {}): string {
  const resources: ResourceLike[] = [...schema.tables, ...schema.views];
  const nameFor = buildNamer(resources);

  const blocks = resources.map((r) => renderInterface(r, nameFor(r)));

  const parts: string[] = [];
  if (opts.header !== false) parts.push(BANNER);
  parts.push(...blocks);
  // A single trailing newline, no matter how many blocks there are.
  return parts.join('\n\n') + '\n';
}

type ResourceLike = TableContext | ViewContext;

function renderInterface(resource: ResourceLike, name: string): string {
  const lines: string[] = [];
  const doc = jsDoc(resource.description, 0);
  if (doc) lines.push(doc);
  lines.push(`export interface ${name} {`);
  for (const column of resource.columns) {
    lines.push(renderField(column));
  }
  lines.push('}');
  return lines.join('\n');
}

function renderField(column: ColumnContext): string {
  const lines: string[] = [];
  const doc = jsDoc(column.description, 2);
  if (doc) lines.push(doc);
  const type = mapColumnType(column) + (column.nullable ? ' | null' : '');
  lines.push(`  ${propertyKey(column.name)}: ${type};`);
  return lines.join('\n');
}

/** Render a COMMENT body as a JSDoc block indented by `indent` spaces, or null
 *  when there is nothing to say. */
function jsDoc(description: string | null, indent: number): string | null {
  if (description === null) return null;
  const trimmed = description.trim();
  if (trimmed === '') return null;
  const pad = ' '.repeat(indent);
  const body = trimmed.split('\n').map((line) => `${pad} * ${line.trimEnd()}`.trimEnd());
  return [`${pad}/**`, ...body, `${pad} */`].join('\n');
}

/** A bare property key when the column name is a plain identifier, otherwise a
 *  quoted key so the output is always valid TypeScript. */
function propertyKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : quotePropertyKey(name);
}

function quotePropertyKey(name: string): string {
  return `'${name.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/** Resolve each resource to a unique interface name: PascalCase of the bare
 *  name, qualified with the schema only when the bare name collides. */
function buildNamer(resources: ResourceLike[]): (r: ResourceLike) => string {
  const bareCounts = new Map<string, number>();
  for (const r of resources) {
    const bare = pascalCase(r.name);
    bareCounts.set(bare, (bareCounts.get(bare) ?? 0) + 1);
  }
  return (r) => {
    const bare = pascalCase(r.name);
    if ((bareCounts.get(bare) ?? 0) > 1) {
      return `${pascalCase(r.schema)}${bare}`;
    }
    return bare;
  };
}

/** Convert an arbitrary SQL identifier to PascalCase, splitting on any run of
 *  non-alphanumeric characters and guarding against a leading digit. */
function pascalCase(identifier: string): string {
  const segments = identifier.split(/[^A-Za-z0-9]+/).filter((s) => s.length > 0);
  const pascal = segments
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
  if (pascal === '') return '_';
  return /^[0-9]/.test(pascal) ? `_${pascal}` : pascal;
}
