import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { readFile, mkdtemp } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { randomBytes } from 'node:crypto';
import type { RawIntrospection } from '@kozou/core';
import * as introspectModule from '@kozou/introspect';
import { codegenCommand } from '../src/commands/codegen.js';

async function makeTempDir(): Promise<string> {
  return mkdtemp(join(tmpdir(), `kozou-codegen-${randomBytes(4).toString('hex')}-`));
}

function makeRawIntrospection(): RawIntrospection {
  return {
    serverVersion: '16.2',
    introspectedAt: '2026-01-01T00:00:00.000Z',
    schemas: ['public'],
    tables: [
      {
        schema: 'public',
        name: 'users',
        comment: 'Application users.',
        columns: [
          {
            name: 'id',
            dataType: 'uuid',
            udtName: 'uuid',
            nullable: false,
            defaultExpr: 'gen_random_uuid()',
            comment: null,
            position: 1,
          },
          {
            name: 'email',
            dataType: 'text',
            udtName: 'text',
            nullable: false,
            defaultExpr: null,
            comment: 'Login email.',
            position: 2,
          },
        ],
        primaryKey: ['id'],
        foreignKeys: [],
        checks: [],
        indexes: [],
        rowCountEstimate: null,
      },
    ],
    views: [],
    enums: [],
    functions: [],
  };
}

describe('codegenCommand', () => {
  const originalEnv = process.env.DATABASE_URL;

  beforeEach(() => {
    process.env.DATABASE_URL = 'postgres://test:test@localhost:5432/test';
    vi.spyOn(introspectModule, 'introspect').mockResolvedValue(makeRawIntrospection());
  });

  afterEach(() => {
    vi.restoreAllMocks();
    process.env.DATABASE_URL = originalEnv;
  });

  it('writes generated row types to stdout by default', async () => {
    let captured = '';
    const stdoutSpy = vi.spyOn(process.stdout, 'write').mockImplementation((chunk) => {
      captured += typeof chunk === 'string' ? chunk : chunk.toString();
      return true;
    });
    await codegenCommand({ config: '/nonexistent/kozou.config.yaml' });
    stdoutSpy.mockRestore();

    expect(captured.endsWith('\n')).toBe(true);
    expect(captured).toContain('Generated by `kozou codegen`');
    expect(captured).toContain('export interface Users {');
    expect(captured).toContain('id: string;');
    expect(captured).toContain('email: string;');
  });

  it('writes generated row types to a file when --output is a path', async () => {
    const dir = await makeTempDir();
    const outFile = join(dir, 'types.ts');
    await codegenCommand({ output: outFile, config: '/nonexistent/kozou.config.yaml' });

    const content = await readFile(outFile, 'utf8');
    expect(content).toContain('export interface Users {');
    expect(content.endsWith('\n')).toBe(true);
  });

  it('introspects the configured connection + schemas', async () => {
    const spy = vi
      .spyOn(introspectModule, 'introspect')
      .mockResolvedValue(makeRawIntrospection());
    const stdoutSpy = vi.spyOn(process.stdout, 'write').mockImplementation(() => true);
    await codegenCommand({ config: '/nonexistent/kozou.config.yaml' });
    stdoutSpy.mockRestore();

    expect(spy).toHaveBeenCalledTimes(1);
    const call = spy.mock.calls[0]![0];
    expect(call.connection).toBe('postgres://test:test@localhost:5432/test');
    expect(call.schemas).toEqual(['public']);
  });
});
