import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { readFile, mkdtemp } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { randomBytes } from 'node:crypto';
import { buildSchemaContext, type RawColumn, type RawIntrospection } from '@kozou/core';
import * as introspectModule from '@kozou/introspect';
import { emitMarkdown } from '../src/docs.js';
import { docsCommand } from '../src/commands/docs.js';

function col(name: string, dataType: string, overrides: Partial<RawColumn> = {}): RawColumn {
  return {
    name,
    dataType,
    udtName: dataType,
    nullable: true,
    defaultExpr: null,
    comment: null,
    position: 1,
    ...overrides,
  };
}

function makeRaw(): RawIntrospection {
  return {
    serverVersion: '16.2',
    introspectedAt: '2026-01-01T00:00:00.000Z',
    schemas: ['public'],
    enums: [{ schema: 'public', name: 'mood', values: ['happy', 'sad'] }],
    functions: [],
    tables: [
      {
        schema: 'public',
        name: 'authors',
        comment:
          'Authors\n\nPeople who write books.\n@ai: prefer vw_active for active authors.\n@policy: never hard-delete an author.',
        primaryKey: ['id'],
        foreignKeys: [],
        checks: [],
        indexes: [],
        rowCountEstimate: null,
        columns: [
          col('id', 'uuid', { nullable: false, defaultExpr: 'gen_random_uuid()' }),
          col('display_name', 'text', {
            nullable: false,
            comment: 'Shown in listings | the public name.',
          }),
          col('deleted_at', 'timestamp with time zone'),
        ],
      },
      {
        schema: 'public',
        name: 'books',
        comment: 'Books for sale.',
        primaryKey: ['id'],
        foreignKeys: [
          {
            name: 'books_author_id_fkey',
            columns: ['author_id'],
            referencedSchema: 'public',
            referencedTable: 'authors',
            referencedColumns: ['id'],
            onDelete: 'NO ACTION',
            onUpdate: 'NO ACTION',
            comment: null,
          },
        ],
        checks: [{ name: 'books_status_check', expression: "status IN ('draft', 'published')" }],
        indexes: [],
        rowCountEstimate: null,
        columns: [
          col('id', 'uuid', { nullable: false }),
          col('author_id', 'uuid', { nullable: false }),
          col('status', 'text', { nullable: false }),
          col('title', 'text', { nullable: false }),
        ],
      },
    ],
    views: [
      {
        schema: 'public',
        name: 'vw_active',
        comment: 'Active (non-deleted) authors.\n@example: All active authors\n  SELECT * FROM vw_active;',
        columns: [col('id', 'uuid', { nullable: false }), col('display_name', 'text')],
        underlyingTables: [{ schema: 'public', name: 'authors' }],
        definition: 'SELECT id, display_name FROM authors WHERE deleted_at IS NULL',
      },
    ],
  };
}

describe('emitMarkdown', () => {
  it('renders a titled, banner-prefixed document with a table of contents', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    expect(md).toContain('# Database schema');
    expect(md).toContain('Generated by `kozou docs`');
    expect(md).toContain('Source schemas: `public`.');
    expect(md).toContain('## Contents');
    expect(md).toContain('(#table-public-authors)');
    expect(md).toContain('(#view-public-vw-active)');
    expect(md).toContain('(#enum-public-mood)');
  });

  it('renders a table section with anchor, columns, PK, and FK', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    expect(md).toContain('<a id="table-public-authors"></a>');
    expect(md).toContain('(`public.authors`)');
    expect(md).toContain('| Column | Type | Null | Default | Key | Description |');
    expect(md).toContain('| `id` | uuid | no | `gen_random_uuid()` | PK |');
    expect(md).toContain('FK → public.authors.id');
  });

  it('documents every member column of a composite foreign key (v1.1)', async () => {
    const raw: RawIntrospection = {
      serverVersion: '16.2',
      introspectedAt: '2026-01-01T00:00:00.000Z',
      schemas: ['public'],
      enums: [],
      functions: [],
      tables: [
        {
          schema: 'public',
          name: 'orders',
          comment: null,
          primaryKey: ['id', 'region'],
          foreignKeys: [],
          checks: [],
          indexes: [],
          rowCountEstimate: null,
          columns: [
            col('id', 'uuid', { nullable: false }),
            col('region', 'text', { nullable: false }),
          ],
        },
        {
          schema: 'public',
          name: 'shipments',
          comment: null,
          primaryKey: ['id'],
          foreignKeys: [
            {
              name: 'shipments_order_fkey',
              columns: ['order_id', 'order_region'],
              referencedSchema: 'public',
              referencedTable: 'orders',
              referencedColumns: ['id', 'region'],
              onDelete: 'NO ACTION',
              onUpdate: 'NO ACTION',
              comment: null,
            },
          ],
          checks: [],
          indexes: [],
          rowCountEstimate: null,
          columns: [
            col('id', 'uuid', { nullable: false }),
            col('order_id', 'uuid', { nullable: false }),
            col('order_region', 'text', { nullable: false }),
          ],
        },
      ],
      views: [],
    };
    const md = emitMarkdown(await buildSchemaContext({ raw }));
    // Both composite member columns document their aligned referenced column —
    // not just the first, and no bare "FK" fallback.
    expect(md).toContain('FK → public.orders.id');
    expect(md).toContain('FK → public.orders.region');
  });

  it('appends the enum domain to a CHECK-constrained column', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    expect(md).toContain('One of: `draft`, `published`.');
  });

  it('escapes a pipe in a description so the table is not broken', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    expect(md).toContain('Shown in listings \\| the public name.');
  });

  it('escapes a backslash before the pipe so a stray "\\|" cannot break the cell', async () => {
    const raw = makeRaw();
    raw.tables[0]!.columns[1]!.comment = 'path\\|pipe';
    const md = emitMarkdown(await buildSchemaContext({ raw }));
    // backslash doubled, then the pipe escaped: `path\\\|pipe`.
    expect(md).toContain('path\\\\\\|pipe');
  });

  it('surfaces @ai notes and @policy rules as structured sections, not raw prose', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    expect(md).toContain('**AI notes:**');
    expect(md).toContain('> prefer vw_active for active authors.');
    expect(md).toContain('**Policies:**');
    expect(md).toContain('- never hard-delete an author.');
    // Tag lines are not duplicated into the prose.
    expect(md).not.toContain('@policy: never hard-delete');
  });

  it('renders a view section with underlying tables, example query, and definition', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    expect(md).toContain('<a id="view-public-vw-active"></a>');
    expect(md).toContain('**Underlying tables:** `public.authors`');
    expect(md).toContain('**Example query — All active authors**');
    expect(md).toContain('SELECT * FROM vw_active;');
    expect(md).toContain('**Definition**');
    expect(md).toContain('SELECT id, display_name FROM authors WHERE deleted_at IS NULL');
  });

  it('renders enum members', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    expect(md).toContain('<a id="enum-public-mood"></a>');
    expect(md).toContain('### `public.mood`');
    expect(md).toContain('- `happy`');
    expect(md).toContain('- `sad`');
  });

  it('handles an empty schema gracefully', async () => {
    const empty: RawIntrospection = {
      serverVersion: '16.2',
      introspectedAt: '2026-01-01T00:00:00.000Z',
      schemas: ['public'],
      tables: [],
      views: [],
      enums: [],
      functions: [],
    };
    const md = emitMarkdown(await buildSchemaContext({ raw: empty }));
    expect(md).toContain('No tables, views, or enums');
  });

  it('emits a Security section + column notes in privilege-aware (annotate) mode', async () => {
    const role = 'analyst';
    const raw = makeRaw();
    raw.tables[0]!.privileges = { role, select: true, insert: false, update: false, delete: false };
    raw.tables[0]!.columns[1]!.comment = 'Public name.\n@ai: never expose in aggregate reports.';
    raw.tables[0]!.columns[1]!.privileges = { insert: false, update: false };
    raw.views[0]!.privileges = { role, select: true, insert: false, update: false, delete: false };
    const md = emitMarkdown(await buildSchemaContext({ raw, privilegeDisplay: 'annotate' }));
    // Per-table Security table, role-labelled.
    expect(md).toContain('**Security**');
    expect(md).toContain('effective privileges for role `analyst`');
    expect(md).toContain('| SELECT | INSERT | UPDATE | DELETE |');
    // Column-level @ai is now surfaced (the docs gap the privilege work closed).
    expect(md).toContain('**Column notes:**');
    expect(md).toContain('never expose in aggregate reports');
  });

  it('omits the Security section in schema-wide mode (default)', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    expect(md).not.toContain('**Security**');
  });

  it('still surfaces column @ai notes even without privileges (schema-wide)', async () => {
    const raw = makeRaw();
    raw.tables[0]!.columns[1]!.comment = 'Public name.\n@ai: never expose in aggregate reports.';
    const md = emitMarkdown(await buildSchemaContext({ raw }));
    expect(md).toContain('**Column notes:**');
    expect(md).toContain('never expose in aggregate reports');
    expect(md).not.toContain('**Security**');
  });

  // Row-level security signal: a per-table line, surfaced
  // only when RLS is enabled, and only on tables. The policy expressions are
  // never read or shown.
  it('renders a Row-level security line when RLS is enabled (with policies)', async () => {
    const raw = makeRaw();
    raw.tables[0]!.rowSecurity = {
      enabled: true,
      forced: false,
      hasPolicies: true,
      deniedCommands: [],
    };
    const md = emitMarkdown(await buildSchemaContext({ raw }));
    expect(md).toContain('**Row-level security**');
    expect(md).toContain('filtered by policy');
  });

  it('names the commands no permissive policy covers', async () => {
    const raw = makeRaw();
    raw.tables[0]!.rowSecurity = {
      enabled: true,
      forced: false,
      hasPolicies: true,
      deniedCommands: ['insert', 'update', 'delete'],
    };
    const md = emitMarkdown(await buildSchemaContext({ raw }));
    expect(md).toContain('No permissive policy covers insert, update, delete');
    expect(md).toContain('matches no rows instead of failing');
    // The INSERT raises per row written, so one that writes none is not refused
    // at all — the line has to say that rather than "a refused INSERT raises".
    expect(md).toContain('only once it writes a row');
    expect(md).not.toContain('A refused INSERT raises');
  });

  it('renders the line for a context compiled before deniedCommands existed', async () => {
    const raw = makeRaw();
    // An older serialized context carries no `deniedCommands`. The type
    // requires the field, so the older shape has to be built by omitting it.
    raw.tables[0]!.rowSecurity = { enabled: true, forced: false, hasPolicies: true } as NonNullable<
      RawIntrospection['tables'][number]['rowSecurity']
    >;
    const md = emitMarkdown(await buildSchemaContext({ raw }));
    expect(md).toContain('**Row-level security**');
    expect(md).toContain('filtered by policy');
    expect(md).not.toContain('No permissive policy covers');
  });

  it('notes default-deny when RLS is enabled with no policy, and forced for the owner', async () => {
    const raw = makeRaw();
    raw.tables[0]!.rowSecurity = {
      enabled: true,
      forced: true,
      hasPolicies: false,
      deniedCommands: ['select', 'insert', 'update', 'delete'],
    };
    const md = emitMarkdown(await buildSchemaContext({ raw }));
    expect(md).toContain('default-deny');
    expect(md).toContain('table owner');
  });

  it('omits the Row-level security line when RLS is disabled', async () => {
    const raw = makeRaw();
    raw.tables[0]!.rowSecurity = {
      enabled: false,
      forced: false,
      hasPolicies: false,
      deniedCommands: [],
    };
    const md = emitMarkdown(await buildSchemaContext({ raw }));
    expect(md).not.toContain('**Row-level security**');
  });
});

describe('emitMarkdown — entity-relationship diagram', () => {
  it('emits a Mermaid erDiagram block under its own heading', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    expect(md).toContain('## Entity-relationship diagram');
    expect(md).toContain('```mermaid');
    expect(md).toContain('erDiagram');
  });

  it('renders an entity block with PK / FK markers and a Mermaid-safe type token', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    expect(md).toContain('  authors {');
    expect(md).toContain('    uuid id PK');
    // "timestamp with time zone" has spaces, illegal in a Mermaid attribute
    // type — it is folded to underscores (the precise type stays in the table).
    expect(md).toContain('    timestamp_with_time_zone deleted_at');
    expect(md).toContain('    uuid author_id FK');
  });

  it('draws a foreign key as a parent→child crow\'s-foot edge (required, many-to-one)', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    // books.author_id is NOT NULL and not unique ⇒ exactly-one parent (`||`),
    // zero-or-more children (`o{`). No FK COMMENT ⇒ labelled with the column.
    expect(md).toContain('  authors ||--o{ books : "author_id"');
  });

  it('marks a nullable foreign key as zero-or-one on the parent side', async () => {
    const raw = makeRaw();
    raw.tables[1]!.columns[1]!.nullable = true; // books.author_id
    const md = emitMarkdown(await buildSchemaContext({ raw }));
    expect(md).toContain('  authors |o--o{ books : "author_id"');
  });

  it('marks a unique foreign key as one-to-one (zero-or-one child)', async () => {
    const raw = makeRaw();
    raw.tables[1]!.indexes = [{ name: 'books_author_uniq', columns: ['author_id'], unique: true }];
    const md = emitMarkdown(await buildSchemaContext({ raw }));
    expect(md).toContain('  authors ||--o| books : "author_id"');
  });

  it('uses the foreign key COMMENT as the edge label when present', async () => {
    const raw = makeRaw();
    raw.tables[1]!.foreignKeys[0]!.comment = 'written by';
    const md = emitMarkdown(await buildSchemaContext({ raw }));
    expect(md).toContain('  authors ||--o{ books : "written by"');
  });

  it('draws a composite foreign key as a single edge naming every member column', async () => {
    const raw: RawIntrospection = {
      serverVersion: '16.2',
      introspectedAt: '2026-01-01T00:00:00.000Z',
      schemas: ['public'],
      enums: [],
      functions: [],
      tables: [
        {
          schema: 'public',
          name: 'orders',
          comment: null,
          primaryKey: ['id', 'region'],
          foreignKeys: [],
          checks: [],
          indexes: [],
          rowCountEstimate: null,
          columns: [
            col('id', 'uuid', { nullable: false }),
            col('region', 'text', { nullable: false }),
          ],
        },
        {
          schema: 'public',
          name: 'shipments',
          comment: null,
          primaryKey: ['id'],
          foreignKeys: [
            {
              name: 'shipments_order_fkey',
              columns: ['order_id', 'order_region'],
              referencedSchema: 'public',
              referencedTable: 'orders',
              referencedColumns: ['id', 'region'],
              onDelete: 'NO ACTION',
              onUpdate: 'NO ACTION',
              comment: null,
            },
          ],
          checks: [],
          indexes: [],
          rowCountEstimate: null,
          columns: [
            col('id', 'uuid', { nullable: false }),
            col('order_id', 'uuid', { nullable: false }),
            col('order_region', 'text', { nullable: false }),
          ],
        },
      ],
      views: [],
    };
    const md = emitMarkdown(await buildSchemaContext({ raw }));
    expect(md).toContain('  orders ||--o{ shipments : "order_id + order_region"');
  });

  it('draws a dotted "derives from" edge from a view to its underlying tables', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    expect(md).toContain('  authors }o..o{ vw_active : "derives from"');
  });

  it('co-locates a legend and the entity @ai / @policy notes under the diagram', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    const er = md.slice(
      md.indexOf('## Entity-relationship diagram'),
      md.indexOf('## Tables'),
    );
    expect(er).toContain('**Legend.**');
    expect(er).toContain('Dotted lines show which tables a view derives from');
    expect(er).toContain('**Where the meaning lives**');
    expect(er).toContain('`public.authors` (table) — *AI:* prefer vw_active for active authors.');
    expect(er).toContain('*Policy:* never hard-delete an author.');
  });

  it('surfaces a source-of-truth view through its @ai note in the diagram notes', async () => {
    const raw = makeRaw();
    raw.views[0]!.comment =
      'Active authors.\n@ai: This is the source of truth for active authors; start here.';
    const md = emitMarkdown(await buildSchemaContext({ raw }));
    expect(md).toContain(
      '`public.vw_active` (view) — *AI:* This is the source of truth for active authors; start here.',
    );
  });

  it('marks a column that is both a primary and a foreign key as "PK, FK"', async () => {
    const raw: RawIntrospection = {
      serverVersion: '16.2',
      introspectedAt: '2026-01-01T00:00:00.000Z',
      schemas: ['public'],
      enums: [],
      functions: [],
      tables: [
        {
          schema: 'public',
          name: 'users',
          comment: null,
          primaryKey: ['id'],
          foreignKeys: [],
          checks: [],
          indexes: [],
          rowCountEstimate: null,
          columns: [col('id', 'uuid', { nullable: false })],
        },
        {
          schema: 'public',
          name: 'profiles',
          comment: null,
          primaryKey: ['user_id'],
          foreignKeys: [
            {
              name: 'profiles_user_fkey',
              columns: ['user_id'],
              referencedSchema: 'public',
              referencedTable: 'users',
              referencedColumns: ['id'],
              onDelete: 'NO ACTION',
              onUpdate: 'NO ACTION',
              comment: null,
            },
          ],
          checks: [],
          indexes: [],
          rowCountEstimate: null,
          columns: [col('user_id', 'uuid', { nullable: false })],
        },
      ],
      views: [],
    };
    const md = emitMarkdown(await buildSchemaContext({ raw }));
    expect(md).toContain('    uuid user_id PK, FK');
  });

  it('prefixes attribute tokens that would not start with a letter (Mermaid-safe)', async () => {
    const raw = makeRaw();
    raw.tables[0]!.columns.push(col('2fa_enabled', 'boolean'));
    raw.tables[0]!.columns.push(col('weird', '128bit'));
    const md = emitMarkdown(await buildSchemaContext({ raw }));
    // A name starting with a digit gets an `x` prefix; a type that would start
    // with a digit gets a `t_` prefix. The precise values stay in the table.
    expect(md).toContain('boolean x2fa_enabled');
    expect(md).toContain('t_128bit weird');
  });

  it('disambiguates entities that collide only after id sanitization', async () => {
    const raw: RawIntrospection = {
      serverVersion: '16.2',
      introspectedAt: '2026-01-01T00:00:00.000Z',
      schemas: ['public'],
      enums: [],
      functions: [],
      tables: [
        {
          schema: 'public',
          name: 'order-item',
          comment: null,
          primaryKey: ['id'],
          foreignKeys: [],
          checks: [],
          indexes: [],
          rowCountEstimate: null,
          columns: [col('id', 'uuid', { nullable: false })],
        },
        {
          schema: 'public',
          name: 'order_item',
          comment: null,
          primaryKey: ['id'],
          foreignKeys: [],
          checks: [],
          indexes: [],
          rowCountEstimate: null,
          columns: [col('id', 'uuid', { nullable: false })],
        },
      ],
      views: [],
    };
    const md = emitMarkdown(await buildSchemaContext({ raw }));
    // Both bare names fold to "order_item"; the second is suffixed so the two
    // distinct tables never share one node.
    expect(md).toContain('  order_item {');
    expect(md).toContain('  order_item_2 {');
  });

  it('draws a foreign key to a table outside the introspected set without merging nodes', async () => {
    const raw: RawIntrospection = {
      serverVersion: '16.2',
      introspectedAt: '2026-01-01T00:00:00.000Z',
      schemas: ['public'],
      enums: [],
      functions: [],
      tables: [
        {
          schema: 'public',
          name: 'books',
          comment: null,
          primaryKey: ['id'],
          foreignKeys: [
            {
              name: 'books_author_fkey',
              columns: ['author_id'],
              referencedSchema: 'other',
              referencedTable: 'authors',
              referencedColumns: ['id'],
              onDelete: 'NO ACTION',
              onUpdate: 'NO ACTION',
              comment: null,
            },
          ],
          checks: [],
          indexes: [],
          rowCountEstimate: null,
          columns: [
            col('id', 'uuid', { nullable: false }),
            col('author_id', 'uuid', { nullable: false }),
          ],
        },
      ],
      views: [],
    };
    const md = emitMarkdown(await buildSchemaContext({ raw }));
    // The edge is drawn (no silent drop) but the external target has no entity
    // block of its own.
    expect(md).toContain('authors ||--o{ books : "author_id"');
    expect(md).not.toContain('  authors {');
  });

  it('omits the diagram for an empty schema', async () => {
    const empty: RawIntrospection = {
      serverVersion: '16.2',
      introspectedAt: '2026-01-01T00:00:00.000Z',
      schemas: ['public'],
      tables: [],
      views: [],
      enums: [],
      functions: [],
    };
    const md = emitMarkdown(await buildSchemaContext({ raw: empty }));
    expect(md).not.toContain('## Entity-relationship diagram');
  });
});

describe('docsCommand', () => {
  const originalEnv = process.env.DATABASE_URL;

  beforeEach(() => {
    process.env.DATABASE_URL = 'postgres://test:test@localhost:5432/test';
    vi.spyOn(introspectModule, 'introspect').mockResolvedValue(makeRaw());
  });

  afterEach(() => {
    vi.restoreAllMocks();
    process.env.DATABASE_URL = originalEnv;
  });

  it('writes the Markdown document to stdout by default', async () => {
    let captured = '';
    const stdoutSpy = vi.spyOn(process.stdout, 'write').mockImplementation((chunk) => {
      captured += typeof chunk === 'string' ? chunk : chunk.toString();
      return true;
    });
    await docsCommand({ config: '/nonexistent/kozou.config.yaml' });
    stdoutSpy.mockRestore();

    expect(captured.endsWith('\n')).toBe(true);
    expect(captured).toContain('# Database schema');
    expect(captured).toContain('(`public.authors`)');
  });

  it('writes the Markdown document to a file when --output is a path', async () => {
    const dir = await mkdtemp(join(tmpdir(), `kozou-docs-${randomBytes(4).toString('hex')}-`));
    const outFile = join(dir, 'SCHEMA.md');
    await docsCommand({ output: outFile, config: '/nonexistent/kozou.config.yaml' });

    const content = await readFile(outFile, 'utf8');
    expect(content).toContain('# Database schema');
    expect(content).toContain('## Tables');
  });

  it('introspects the configured connection + schemas', async () => {
    const spy = vi.spyOn(introspectModule, 'introspect').mockResolvedValue(makeRaw());
    const stdoutSpy = vi.spyOn(process.stdout, 'write').mockImplementation(() => true);
    await docsCommand({ config: '/nonexistent/kozou.config.yaml' });
    stdoutSpy.mockRestore();

    expect(spy).toHaveBeenCalledTimes(1);
    const callArg = spy.mock.calls[0]![0];
    expect(callArg.connection).toBe('postgres://test:test@localhost:5432/test');
    expect(callArg.schemas).toEqual(['public']);
  });
});
