import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { readFile, mkdtemp } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { randomBytes } from 'node:crypto';
import { buildSchemaContext, type RawColumn, type RawIntrospection } from '@kozou/core';
import * as introspectModule from '@kozou/introspect';
import { emitMarkdown } from '../src/docs.js';
import { docsCommand } from '../src/commands/docs.js';

function col(name: string, dataType: string, overrides: Partial<RawColumn> = {}): RawColumn {
  return {
    name,
    dataType,
    udtName: dataType,
    nullable: true,
    defaultExpr: null,
    comment: null,
    position: 1,
    ...overrides,
  };
}

function makeRaw(): RawIntrospection {
  return {
    serverVersion: '16.2',
    introspectedAt: '2026-01-01T00:00:00.000Z',
    schemas: ['public'],
    enums: [{ schema: 'public', name: 'mood', values: ['happy', 'sad'] }],
    functions: [],
    tables: [
      {
        schema: 'public',
        name: 'authors',
        comment:
          'Authors\n\nPeople who write books.\n@ai: prefer vw_active for active authors.\n@policy: never hard-delete an author.',
        primaryKey: ['id'],
        foreignKeys: [],
        checks: [],
        indexes: [],
        rowCountEstimate: null,
        columns: [
          col('id', 'uuid', { nullable: false, defaultExpr: 'gen_random_uuid()' }),
          col('display_name', 'text', {
            nullable: false,
            comment: 'Shown in listings | the public name.',
          }),
          col('deleted_at', 'timestamp with time zone'),
        ],
      },
      {
        schema: 'public',
        name: 'books',
        comment: 'Books for sale.',
        primaryKey: ['id'],
        foreignKeys: [
          {
            name: 'books_author_id_fkey',
            columns: ['author_id'],
            referencedSchema: 'public',
            referencedTable: 'authors',
            referencedColumns: ['id'],
            onDelete: 'NO ACTION',
            onUpdate: 'NO ACTION',
            comment: null,
          },
        ],
        checks: [{ name: 'books_status_check', expression: "status IN ('draft', 'published')" }],
        indexes: [],
        rowCountEstimate: null,
        columns: [
          col('id', 'uuid', { nullable: false }),
          col('author_id', 'uuid', { nullable: false }),
          col('status', 'text', { nullable: false }),
          col('title', 'text', { nullable: false }),
        ],
      },
    ],
    views: [
      {
        schema: 'public',
        name: 'vw_active',
        comment: 'Active (non-deleted) authors.\n@example: All active authors\n  SELECT * FROM vw_active;',
        columns: [col('id', 'uuid', { nullable: false }), col('display_name', 'text')],
        underlyingTables: [{ schema: 'public', name: 'authors' }],
        definition: 'SELECT id, display_name FROM authors WHERE deleted_at IS NULL',
      },
    ],
  };
}

describe('emitMarkdown', () => {
  it('renders a titled, banner-prefixed document with a table of contents', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    expect(md).toContain('# Database schema');
    expect(md).toContain('Generated by `kozou docs`');
    expect(md).toContain('Source schemas: `public`.');
    expect(md).toContain('## Contents');
    expect(md).toContain('(#table-public-authors)');
    expect(md).toContain('(#view-public-vw-active)');
    expect(md).toContain('(#enum-public-mood)');
  });

  it('renders a table section with anchor, columns, PK, and FK', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    expect(md).toContain('<a id="table-public-authors"></a>');
    expect(md).toContain('(`public.authors`)');
    expect(md).toContain('| Column | Type | Null | Default | Key | Description |');
    expect(md).toContain('| `id` | uuid | no | `gen_random_uuid()` | PK |');
    expect(md).toContain('FK → public.authors.id');
  });

  it('appends the enum domain to a CHECK-constrained column', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    expect(md).toContain('One of: `draft`, `published`.');
  });

  it('escapes a pipe in a description so the table is not broken', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    expect(md).toContain('Shown in listings \\| the public name.');
  });

  it('escapes a backslash before the pipe so a stray "\\|" cannot break the cell', async () => {
    const raw = makeRaw();
    raw.tables[0]!.columns[1]!.comment = 'path\\|pipe';
    const md = emitMarkdown(await buildSchemaContext({ raw }));
    // backslash doubled, then the pipe escaped: `path\\\|pipe`.
    expect(md).toContain('path\\\\\\|pipe');
  });

  it('surfaces @ai notes and @policy rules as structured sections, not raw prose', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    expect(md).toContain('**AI notes:**');
    expect(md).toContain('> prefer vw_active for active authors.');
    expect(md).toContain('**Policies:**');
    expect(md).toContain('- never hard-delete an author.');
    // Tag lines are not duplicated into the prose.
    expect(md).not.toContain('@policy: never hard-delete');
  });

  it('renders a view section with underlying tables, example query, and definition', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    expect(md).toContain('<a id="view-public-vw-active"></a>');
    expect(md).toContain('**Underlying tables:** `public.authors`');
    expect(md).toContain('**Example query — All active authors**');
    expect(md).toContain('SELECT * FROM vw_active;');
    expect(md).toContain('**Definition**');
    expect(md).toContain('SELECT id, display_name FROM authors WHERE deleted_at IS NULL');
  });

  it('renders enum members', async () => {
    const md = emitMarkdown(await buildSchemaContext({ raw: makeRaw() }));
    expect(md).toContain('<a id="enum-public-mood"></a>');
    expect(md).toContain('### `public.mood`');
    expect(md).toContain('- `happy`');
    expect(md).toContain('- `sad`');
  });

  it('handles an empty schema gracefully', async () => {
    const empty: RawIntrospection = {
      serverVersion: '16.2',
      introspectedAt: '2026-01-01T00:00:00.000Z',
      schemas: ['public'],
      tables: [],
      views: [],
      enums: [],
      functions: [],
    };
    const md = emitMarkdown(await buildSchemaContext({ raw: empty }));
    expect(md).toContain('No tables, views, or enums');
  });
});

describe('docsCommand', () => {
  const originalEnv = process.env.DATABASE_URL;

  beforeEach(() => {
    process.env.DATABASE_URL = 'postgres://test:test@localhost:5432/test';
    vi.spyOn(introspectModule, 'introspect').mockResolvedValue(makeRaw());
  });

  afterEach(() => {
    vi.restoreAllMocks();
    process.env.DATABASE_URL = originalEnv;
  });

  it('writes the Markdown document to stdout by default', async () => {
    let captured = '';
    const stdoutSpy = vi.spyOn(process.stdout, 'write').mockImplementation((chunk) => {
      captured += typeof chunk === 'string' ? chunk : chunk.toString();
      return true;
    });
    await docsCommand({ config: '/nonexistent/kozou.config.yaml' });
    stdoutSpy.mockRestore();

    expect(captured.endsWith('\n')).toBe(true);
    expect(captured).toContain('# Database schema');
    expect(captured).toContain('(`public.authors`)');
  });

  it('writes the Markdown document to a file when --output is a path', async () => {
    const dir = await mkdtemp(join(tmpdir(), `kozou-docs-${randomBytes(4).toString('hex')}-`));
    const outFile = join(dir, 'SCHEMA.md');
    await docsCommand({ output: outFile, config: '/nonexistent/kozou.config.yaml' });

    const content = await readFile(outFile, 'utf8');
    expect(content).toContain('# Database schema');
    expect(content).toContain('## Tables');
  });

  it('introspects the configured connection + schemas', async () => {
    const spy = vi.spyOn(introspectModule, 'introspect').mockResolvedValue(makeRaw());
    const stdoutSpy = vi.spyOn(process.stdout, 'write').mockImplementation(() => true);
    await docsCommand({ config: '/nonexistent/kozou.config.yaml' });
    stdoutSpy.mockRestore();

    expect(spy).toHaveBeenCalledTimes(1);
    const callArg = spy.mock.calls[0]![0];
    expect(callArg.connection).toBe('postgres://test:test@localhost:5432/test');
    expect(callArg.schemas).toEqual(['public']);
  });
});
