import { describe, it, expect } from 'vitest';
import { mkdtemp, writeFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { randomBytes } from 'node:crypto';
import ts from 'typescript';
import { buildSchemaContext, type RawColumn, type RawIntrospection } from '@kozou/core';
import { emitRowTypes } from '../src/index.js';

function col(name: string, dataType: string, overrides: Partial<RawColumn> = {}): RawColumn {
  return {
    name,
    dataType,
    udtName: dataType,
    nullable: true,
    defaultExpr: null,
    comment: null,
    position: 1,
    ...overrides,
  };
}

// A schema exercising every branch of the dataType -> TS mapping, plus a
// CHECK-derived enum, a nullable column, a quoted-key column, and a view.
const RAW: RawIntrospection = {
  serverVersion: '16.2',
  introspectedAt: '2026-01-01T00:00:00.000Z',
  schemas: ['public'],
  enums: [],
  functions: [],
  tables: [
    {
      schema: 'public',
      name: 'authors',
      comment: 'Authors of books.',
      primaryKey: ['id'],
      foreignKeys: [],
      checks: [],
      indexes: [],
      rowCountEstimate: null,
      columns: [
        col('id', 'uuid', { nullable: false, defaultExpr: 'gen_random_uuid()' }),
        col('display_name', 'text', { nullable: false, comment: 'Shown in listings.' }),
        col('rating', 'numeric(3,2)'),
        col('login_count', 'integer', { nullable: false }),
        col('big_id', 'bigint'),
        col('active', 'boolean', { nullable: false }),
        col('created_at', 'timestamp with time zone', { nullable: false }),
        col('metadata', 'jsonb'),
        col('tags', 'text[]'),
        col('search', 'tsvector'),
        col('weird name', 'text'),
      ],
    },
    {
      schema: 'public',
      name: 'inventory_items',
      comment: null,
      primaryKey: ['id'],
      foreignKeys: [],
      checks: [
        { name: 'inventory_items_status_check', expression: "status IN ('for_sale', 'reserved', 'sold')" },
      ],
      indexes: [],
      rowCountEstimate: null,
      columns: [
        col('id', 'uuid', { nullable: false }),
        col('status', 'text', { nullable: false }),
      ],
    },
  ],
  views: [
    {
      schema: 'public',
      name: 'vw_active',
      comment: 'Active authors.',
      columns: [col('id', 'uuid', { nullable: false }), col('display_name', 'text')],
      underlyingTables: [{ schema: 'public', name: 'authors' }],
      definition: 'SELECT 1',
    },
  ],
};

describe('emitRowTypes', () => {
  it('emits one interface per table and view', async () => {
    const out = emitRowTypes(await buildSchemaContext({ raw: RAW }));
    expect(out).toContain('export interface Authors {');
    expect(out).toContain('export interface InventoryItems {');
    expect(out).toContain('export interface VwActive {');
  });

  it('maps each PostgreSQL dataType to its over-the-wire TypeScript type', async () => {
    const out = emitRowTypes(await buildSchemaContext({ raw: RAW }));
    expect(out).toContain('id: string;'); // uuid
    expect(out).toContain('display_name: string;'); // text, not null
    expect(out).toContain('rating: string | null;'); // numeric -> string, nullable
    expect(out).toContain('login_count: number;'); // integer
    expect(out).toContain('big_id: string | null;'); // bigint -> string
    expect(out).toContain('active: boolean;');
    expect(out).toContain('created_at: string;'); // timestamptz -> ISO string
    expect(out).toContain('metadata: unknown | null;'); // jsonb
    expect(out).toContain('tags: string[] | null;'); // text[]
    expect(out).toContain('search: unknown | null;'); // unmapped type -> unknown
  });

  it('renders a CHECK-derived enum as an inline string-literal union', async () => {
    const out = emitRowTypes(await buildSchemaContext({ raw: RAW }));
    expect(out).toContain("status: 'for_sale' | 'reserved' | 'sold';");
  });

  it('quotes a property key that is not a plain identifier', async () => {
    const out = emitRowTypes(await buildSchemaContext({ raw: RAW }));
    expect(out).toContain("'weird name': string | null;");
  });

  it('carries the COMMENT body into a JSDoc block', async () => {
    const out = emitRowTypes(await buildSchemaContext({ raw: RAW }));
    expect(out).toContain('* Authors of books.');
    expect(out).toContain('* Shown in listings.');
  });

  it('includes the banner by default and omits it when header is false', async () => {
    const ctx = await buildSchemaContext({ raw: RAW });
    expect(emitRowTypes(ctx)).toContain('Generated by `kozou codegen`');
    const noHeader = emitRowTypes(ctx, { header: false });
    expect(noHeader).not.toContain('Generated by');
    expect(noHeader).toContain('export interface Authors {');
  });

  it('qualifies colliding bare names by schema and guards odd identifiers', async () => {
    const raw: RawIntrospection = {
      serverVersion: '16.2',
      introspectedAt: '2026-01-01T00:00:00.000Z',
      schemas: ['public', 'shop'],
      enums: [],
      functions: [],
      tables: ['public', 'shop'].map((schema) => ({
        schema,
        name: 'items',
        comment: null,
        primaryKey: ['id'],
        foreignKeys: [],
        checks: [],
        indexes: [],
        rowCountEstimate: null,
        columns: [col('id', 'uuid', { nullable: false })],
      })),
      views: [],
    };
    // A leading-digit name and a punctuation-only name exercise the identifier
    // guards in the namer.
    raw.tables.push(
      {
        schema: 'public',
        name: '1_weird',
        comment: null,
        primaryKey: [],
        foreignKeys: [],
        checks: [],
        indexes: [],
        rowCountEstimate: null,
        columns: [col('id', 'uuid', { nullable: false })],
      },
      {
        schema: 'public',
        name: '%',
        comment: null,
        primaryKey: [],
        foreignKeys: [],
        checks: [],
        indexes: [],
        rowCountEstimate: null,
        columns: [col('id', 'uuid', { nullable: false })],
      },
    );
    const out = emitRowTypes(await buildSchemaContext({ raw }));
    expect(out).toContain('export interface PublicItems {');
    expect(out).toContain('export interface ShopItems {');
    expect(out).toContain('export interface _1Weird {');
    expect(out).toContain('export interface _ {');
  });

  it('produces a module that type-checks under strict TypeScript', async () => {
    const out = emitRowTypes(await buildSchemaContext({ raw: RAW }));
    const diagnostics = await typeCheck(out);
    const messages = diagnostics.map((d) =>
      ts.flattenDiagnosticMessageText(d.messageText, '\n'),
    );
    expect(messages).toEqual([]);
  });
});

/** Write the generated source to a temp file and run a strict TypeScript
 *  program over it, returning any pre-emit diagnostics. */
async function typeCheck(source: string): Promise<readonly ts.Diagnostic[]> {
  const dir = await mkdtemp(join(tmpdir(), `kozou-codegen-${randomBytes(4).toString('hex')}-`));
  const file = join(dir, 'generated.ts');
  try {
    await writeFile(file, source, 'utf8');
    const program = ts.createProgram([file], {
      noEmit: true,
      strict: true,
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.ESNext,
      moduleResolution: ts.ModuleResolutionKind.Bundler,
      skipLibCheck: true,
    });
    return ts.getPreEmitDiagnostics(program);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}
