// Render a human-readable Markdown document from a SchemaContext.
//
// This is the "docs" emit target (product_architecture_v3 §3.4): alongside the
// Admin UI, MCP context, REST API, and TypeScript types, Kozou turns the same
// DDL + COMMENT into a schema document a person can read, commit, and publish.
//
// Pure function — no I/O — so the `kozou docs` CLI (and tests) drive it
// directly. Content mirrors what the MCP `describe_table` / `describe_view` /
// `get_concept_context` tools surface, formatted for human reading.

import type {
  SchemaContext,
  TableContext,
  ViewContext,
  ColumnContext,
  EnumContext,
  RelationContext,
} from '@kozou/core';

const BANNER = '> Generated by `kozou docs` from PostgreSQL DDL + COMMENT. Do not edit by hand.';

export function emitMarkdown(schema: SchemaContext): string {
  // 1:1 view -> concept, used to surface @example: queries on views.
  const examplesByView = new Map<string, { description: string; sql: string }[]>();
  for (const c of schema.concepts) examplesByView.set(c.name, c.exampleQueries);

  const sections: string[] = ['# Database schema', BANNER];

  const sourceSchemas = schema.meta.sourceSchemas;
  if (sourceSchemas.length > 0) {
    sections.push(`Source schemas: ${sourceSchemas.map(code).join(', ')}.`);
  }

  sections.push(renderContents(schema));

  if (schema.tables.length > 0) {
    sections.push('## Tables');
    for (const t of schema.tables) sections.push(renderTable(t));
  }
  if (schema.views.length > 0) {
    sections.push('## Views');
    for (const v of schema.views) sections.push(renderView(v, examplesByView.get(v.name) ?? []));
  }
  if (schema.enums.length > 0) {
    sections.push('## Enums');
    for (const e of schema.enums) sections.push(renderEnum(e));
  }
  if (schema.tables.length === 0 && schema.views.length === 0 && schema.enums.length === 0) {
    sections.push('_No tables, views, or enums were found in the introspected schema._');
  }

  return sections.join('\n\n') + '\n';
}

function renderContents(schema: SchemaContext): string {
  const lines = ['## Contents'];
  const group = (
    title: string,
    items: { label: string; anchor: string }[],
  ): void => {
    if (items.length === 0) return;
    lines.push('', `**${title}**`, '');
    for (const it of items) lines.push(`- [${escapeInline(it.label)}](#${it.anchor})`);
  };
  group(
    'Tables',
    schema.tables.map((t) => ({ label: t.label, anchor: tableAnchor(t) })),
  );
  group(
    'Views',
    schema.views.map((v) => ({ label: v.label, anchor: viewAnchor(v) })),
  );
  group(
    'Enums',
    schema.enums.map((e) => ({ label: `${e.schema}.${e.name}`, anchor: enumAnchor(e) })),
  );
  return lines.join('\n');
}

function renderTable(t: TableContext): string {
  const out: string[] = [
    `<a id="${tableAnchor(t)}"></a>`,
    `### ${escapeInline(t.label)} (${code(t.qualifiedName)})`,
  ];
  pushProse(out, t.description);
  pushAiNotes(out, t.aiDescription);
  pushPolicies(out, t.policy ?? []);
  out.push(renderColumnsTable(t.columns, t.relations));
  return out.join('\n\n');
}

function renderView(v: ViewContext, examples: { description: string; sql: string }[]): string {
  const out: string[] = [
    `<a id="${viewAnchor(v)}"></a>`,
    `### ${escapeInline(v.label)} (${code(v.qualifiedName)})`,
  ];
  pushProse(out, v.description);
  pushAiNotes(out, v.aiDescription);
  pushPolicies(out, v.policy ?? []);
  if (v.underlyingTables.length > 0) {
    const tables = v.underlyingTables.map((u) => code(`${u.schema}.${u.name}`)).join(', ');
    out.push(`**Underlying tables:** ${tables}`);
  }
  out.push(renderColumnsTable(v.columns, []));
  for (const ex of examples) {
    out.push(`**Example query — ${escapeInline(ex.description)}**`);
    out.push(fencedSql(ex.sql));
  }
  out.push('**Definition**');
  out.push(fencedSql(v.rawView.definition));
  return out.join('\n\n');
}

function renderEnum(e: EnumContext): string {
  const out: string[] = [
    `<a id="${enumAnchor(e)}"></a>`,
    `### ${code(`${e.schema}.${e.name}`)}`,
  ];
  out.push(e.values.map((val) => `- ${code(val)}`).join('\n'));
  return out.join('\n\n');
}

function renderColumnsTable(columns: ColumnContext[], relations: RelationContext[]): string {
  // Map each FK column to its positionally-aligned referenced column. A
  // composite FK contributes every member column (not just the first), so the
  // Markdown agrees with the API / MCP relation metadata.
  const fkRefByColumn = new Map<string, { schema: string; table: string; column: string }>();
  for (const rel of relations) {
    const fields = rel.fields ?? [rel.field];
    const refCols = rel.references.columns ?? [rel.references.column];
    fields.forEach((field, i) => {
      fkRefByColumn.set(field, {
        schema: rel.references.schema,
        table: rel.references.table,
        column: refCols[i]!,
      });
    });
  }

  const header = '| Column | Type | Null | Default | Key | Description |';
  const divider = '| --- | --- | --- | --- | --- | --- |';
  const rows = columns.map((c) => {
    const key = columnKey(c, fkRefByColumn.get(c.name));
    const def = c.defaultExpr ? code(c.defaultExpr) : '';
    const desc = columnDescription(c);
    return `| ${code(c.name)} | ${escapeCell(c.dataType)} | ${c.nullable ? 'yes' : 'no'} | ${def} | ${key} | ${desc} |`;
  });
  return [header, divider, ...rows].join('\n');
}

function columnKey(
  column: ColumnContext,
  ref: { schema: string; table: string; column: string } | undefined,
): string {
  const parts: string[] = [];
  if (column.isPrimaryKey) parts.push('PK');
  if (ref) {
    parts.push(`FK → ${escapeCell(`${ref.schema}.${ref.table}.${ref.column}`)}`);
  } else if (column.isForeignKey) {
    parts.push('FK');
  }
  return parts.join(', ');
}

/** A one-line, table-cell-safe description: cleaned of tag lines, with the
 *  enum domain appended when present. */
function columnDescription(column: ColumnContext): string {
  const prose = cleanProse(column.description);
  const parts: string[] = [];
  if (prose) parts.push(escapeCell(prose));
  if (column.enumValues && column.enumValues.length > 0) {
    parts.push(`One of: ${column.enumValues.map(code).join(', ')}.`);
  }
  return parts.join(' ');
}

function pushProse(out: string[], description: string | null): void {
  const prose = cleanProse(description);
  if (prose) out.push(prose);
}

function pushAiNotes(out: string[], aiDescription: string | null): void {
  if (!aiDescription) return;
  const quoted = aiDescription
    .split('\n')
    .map((line) => `> ${line}`)
    .join('\n');
  out.push(`**AI notes:**\n\n${quoted}`);
}

function pushPolicies(out: string[], policies: string[]): void {
  if (policies.length === 0) return;
  const list = policies.map((p) => `- ${escapeInline(p)}`).join('\n');
  out.push(`**Policies:**\n\n${list}`);
}

/** Drop `@ai:` / `@policy:` / other tag lines from a COMMENT body, leaving the
 *  human prose. Tag lines are surfaced separately as structured sections. */
function cleanProse(description: string | null): string | null {
  if (description === null) return null;
  const kept = description.split('\n').filter((line) => !line.trim().startsWith('@'));
  const text = kept.join('\n').trim();
  return text === '' ? null : text;
}

function fencedSql(sql: string): string {
  return ['```sql', sql.trim(), '```'].join('\n');
}

function code(value: string): string {
  return `\`${value}\``;
}

/** Escape a value for inline Markdown text (outside a table cell). */
function escapeInline(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}

/** Collapse whitespace and escape a value so it is safe inside a Markdown
 *  table cell. The backslash is escaped first so a pre-existing `\` cannot
 *  swallow the escape we add for the pipe. All regexes are linear (single,
 *  unanchored) — no ReDoS. */
function escapeCell(value: string): string {
  return value
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\\/g, '\\\\')
    .replace(/\|/g, '\\|');
}

function tableAnchor(t: TableContext): string {
  return `table-${slug(t.qualifiedName)}`;
}

function viewAnchor(v: ViewContext): string {
  return `view-${slug(v.qualifiedName)}`;
}

function enumAnchor(e: EnumContext): string {
  return `enum-${slug(`${e.schema}.${e.name}`)}`;
}

/** A deterministic, renderer-independent anchor slug. Paired with an explicit
 *  `<a id>` so the table-of-contents links resolve regardless of how a given
 *  Markdown renderer auto-slugs headings. */
function slug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+/, '')
    .replace(/-+$/, '');
}
