// Render a human-readable Markdown document from a SchemaContext.
//
// This is the "docs" emit target: alongside the
// Admin UI, MCP context, REST API, and TypeScript types, Kozou turns the same
// DDL + COMMENT into a schema document a person can read, commit, and publish.
//
// Pure function — no I/O — so the `kozou docs` CLI (and tests) drive it
// directly. Content mirrors what the MCP `describe_table` / `describe_view` /
// `get_concept_context` tools surface, formatted for human reading.

import type {
  SchemaContext,
  TableContext,
  ViewContext,
  ColumnContext,
  EnumContext,
  RelationContext,
  RelationPrivileges,
  RowSecurity,
} from '@kozou/core';

const BANNER = '> Generated by `kozou docs` from PostgreSQL DDL + COMMENT. Do not edit by hand.';

export function emitMarkdown(schema: SchemaContext): string {
  // 1:1 view -> concept, used to surface @example: queries on views.
  const examplesByView = new Map<string, { description: string; sql: string }[]>();
  for (const c of schema.concepts) examplesByView.set(c.name, c.exampleQueries);

  const sections: string[] = ['# Database schema', BANNER];

  const sourceSchemas = schema.meta.sourceSchemas;
  if (sourceSchemas.length > 0) {
    sections.push(`Source schemas: ${sourceSchemas.map(code).join(', ')}.`);
  }

  sections.push(renderContents(schema));

  const er = renderErDiagram(schema);
  if (er) sections.push(er);

  if (schema.tables.length > 0) {
    sections.push('## Tables');
    for (const t of schema.tables) sections.push(renderTable(t));
  }
  if (schema.views.length > 0) {
    sections.push('## Views');
    for (const v of schema.views) sections.push(renderView(v, examplesByView.get(v.name) ?? []));
  }
  if (schema.enums.length > 0) {
    sections.push('## Enums');
    for (const e of schema.enums) sections.push(renderEnum(e));
  }
  if (schema.tables.length === 0 && schema.views.length === 0 && schema.enums.length === 0) {
    sections.push('_No tables, views, or enums were found in the introspected schema._');
  }

  return sections.join('\n\n') + '\n';
}

function renderContents(schema: SchemaContext): string {
  const lines = ['## Contents'];
  const group = (
    title: string,
    items: { label: string; anchor: string }[],
  ): void => {
    if (items.length === 0) return;
    lines.push('', `**${title}**`, '');
    for (const it of items) lines.push(`- [${escapeInline(it.label)}](#${it.anchor})`);
  };
  group(
    'Tables',
    schema.tables.map((t) => ({ label: t.label, anchor: tableAnchor(t) })),
  );
  group(
    'Views',
    schema.views.map((v) => ({ label: v.label, anchor: viewAnchor(v) })),
  );
  group(
    'Enums',
    schema.enums.map((e) => ({ label: `${e.schema}.${e.name}`, anchor: enumAnchor(e) })),
  );
  return lines.join('\n');
}

/** An entity-relationship diagram of the schema, emitted as a Mermaid
 *  `erDiagram` fenced block (GitHub, many Markdown editors, and static-site
 *  generators render Mermaid natively). This is "another faithful form": the
 *  same SchemaContext the other surfaces read, drawn.
 *
 *  It is meaning-laden, not a bare foreign-key graph: views — Kozou's named
 *  business concepts — are entities too, linked by a dotted edge to the tables
 *  they derive from, and a legend points at the entities carrying `@ai` /
 *  `@policy` guidance so the diagram and its meaning sit on the same page.
 *  Read-only / stateless / no new introspection — built entirely from the
 *  existing SchemaContext. Returns null for an empty schema. */
function renderErDiagram(schema: SchemaContext): string | null {
  if (schema.tables.length === 0 && schema.views.length === 0) return null;

  // Entity-id scheme: bare names read best, but two relations in different
  // schemas can share a name — fall back to schema-qualified ids for everyone
  // so the diagram is readable. Sanitization can still collide ("order-item"
  // and "order_item" both fold to "order_item"), so ids are allocated through
  // a collision-safe map keyed by qualified name: the same relation always
  // resolves to one id, and two distinct relations never share a node.
  const nameCounts = new Map<string, number>();
  for (const t of schema.tables) nameCounts.set(t.name, (nameCounts.get(t.name) ?? 0) + 1);
  for (const v of schema.views) nameCounts.set(v.name, (nameCounts.get(v.name) ?? 0) + 1);
  const qualify = [...nameCounts.values()].some((n) => n > 1);
  const idByQualified = new Map<string, string>();
  const usedIds = new Set<string>();
  const entityId = (sch: string, name: string): string => {
    // Key on a NUL separator, which cannot appear in a PostgreSQL identifier,
    // so distinct (schema, name) pairs never collide on the key itself (a "."
    // could, since a quoted identifier may legally contain one).
    const qualified = `${sch}\u0000${name}`;
    const existing = idByQualified.get(qualified);
    if (existing) return existing;
    const base = mermaidIdent(qualify ? `${sch}_${name}` : name);
    let id = base;
    for (let n = 2; usedIds.has(id); n += 1) id = `${base}_${n}`;
    usedIds.add(id);
    idByQualified.set(qualified, id);
    return id;
  };
  // Allocate ids for the emitted entities first, so a foreign key to a table
  // outside the introspected set gets a fresh (non-colliding) node rather than
  // silently merging into an emitted one.
  for (const t of schema.tables) entityId(t.schema, t.name);
  for (const v of schema.views) entityId(v.schema, v.name);

  const diagram: string[] = ['erDiagram'];

  // Entities — tables then views. Attributes are the columns (a Mermaid-safe
  // type token + name + a single key marker); the precise type and full PK/FK
  // detail stay in the per-entity table below the diagram.
  for (const t of schema.tables) diagram.push(...entityBlock(entityId(t.schema, t.name), t.columns));
  for (const v of schema.views) diagram.push(...entityBlock(entityId(v.schema, v.name), v.columns));

  // Foreign-key edges — parent (referenced) to child (holder), crow's-foot
  // cardinality, labelled with the FK COMMENT meaning or the FK column(s). A
  // composite FK is one edge (every member column in the label), matching the
  // relation metadata the API / MCP surface.
  for (const t of schema.tables) {
    for (const rel of t.relations) {
      const fields = rel.fields ?? [rel.field];
      // Required when every member column is NOT NULL: each child then has
      // exactly one parent (`||`); a nullable member makes it zero-or-one
      // (`|o`).
      const required = fields.every((f) => {
        const col = t.columns.find((c) => c.name === f);
        return col ? !col.nullable : false;
      });
      const parentCard = required ? '||' : '|o';
      const childCard = rel.cardinality === 'one-to-one' ? 'o|' : 'o{';
      const parent = entityId(rel.references.schema, rel.references.table);
      const child = entityId(t.schema, t.name);
      diagram.push(`  ${parent} ${parentCard}--${childCard} ${child} : ${relationLabel(rel, fields)}`);
    }
  }

  // View derive edges (dotted, non-identifying) — which tables a view is built
  // from, the part a plain foreign-key-graph tool omits.
  for (const v of schema.views) {
    const viewId = entityId(v.schema, v.name);
    for (const u of v.underlyingTables) {
      const src = entityId(u.schema, u.name);
      if (src === viewId) continue; // a view selecting from itself: skip the self-edge
      diagram.push(`  ${src} }o..o{ ${viewId} : "derives from"`);
    }
  }

  const out: string[] = [
    '## Entity-relationship diagram',
    ['```mermaid', ...diagram, '```'].join('\n'),
    erLegend(schema),
  ];
  const meaning = erMeaningNotes(schema);
  if (meaning) out.push(meaning);
  return out.join('\n\n');
}

/** One entity block: the id, then a line per column. An entity with no columns
 *  is declared bare (an empty `{}` block is rejected by some Mermaid versions). */
function entityBlock(id: string, columns: ColumnContext[]): string[] {
  if (columns.length === 0) return [`  ${id}`];
  const lines = [`  ${id} {`];
  for (const c of columns) {
    const type = mermaidType(c.effectiveType ?? c.dataType);
    // A column can be both a primary and a foreign key (e.g. a join table);
    // Mermaid takes comma-separated key markers, so surface both.
    const markers: string[] = [];
    if (c.isPrimaryKey) markers.push('PK');
    if (c.isForeignKey) markers.push('FK');
    const key = markers.length > 0 ? ` ${markers.join(', ')}` : '';
    lines.push(`    ${type} ${mermaidIdent(c.name)}${key}`);
  }
  lines.push('  }');
  return lines;
}

/** A quoted relationship label: the FK's COMMENT meaning when present,
 *  otherwise the foreign-key column(s). Always quoted (so spaces are safe),
 *  truncated, with any embedded double-quote neutralised. */
function relationLabel(rel: RelationContext, fields: string[]): string {
  const text = rel.meaning ? oneLine(rel.meaning) : fields.join(' + ');
  return `"${truncate(text, 60).replace(/"/g, "'")}"`;
}

function erLegend(schema: SchemaContext): string {
  let prose =
    "**Legend.** Solid lines are foreign keys — crow's-foot cardinality, " +
    "labelled with the foreign key's COMMENT when set, otherwise its column(s).";
  if (schema.views.length > 0) {
    prose +=
      ' Dotted lines show which tables a view derives from. Views are Kozou’s ' +
      'named business concepts — prefer them over re-deriving rules from base tables.';
  }
  return prose;
}

/** Entity-level `@ai` / `@policy` notes, co-located right under the diagram so
 *  the structure and its meaning sit together. One line per table/view that
 *  carries guidance (a source-of-truth view surfaces here via its `@ai` note);
 *  the full notes live in the sections below. Column-level notes stay in each
 *  entity's "Column notes". */
function erMeaningNotes(schema: SchemaContext): string | null {
  const items: string[] = [];
  const add = (
    qualifiedName: string,
    kind: 'table' | 'view',
    ai: string | null,
    policy: string[] | undefined,
  ): void => {
    const parts: string[] = [];
    if (ai) parts.push(`*AI:* ${escapeInline(truncate(oneLine(ai)))}`);
    if (policy && policy.length > 0) {
      parts.push(`*Policy:* ${escapeInline(truncate(oneLine(policy.join(' '))))}`);
    }
    if (parts.length > 0) items.push(`- ${code(qualifiedName)} (${kind}) — ${parts.join(' ')}`);
  };
  for (const t of schema.tables) add(t.qualifiedName, 'table', t.aiDescription, t.policy);
  for (const v of schema.views) add(v.qualifiedName, 'view', v.aiDescription, v.policy);
  if (items.length === 0) return null;
  return `**Where the meaning lives** (full notes in the sections below):\n\n${items.join('\n')}`;
}

function renderTable(t: TableContext): string {
  const out: string[] = [
    `<a id="${tableAnchor(t)}"></a>`,
    `### ${escapeInline(t.label)} (${code(t.qualifiedName)})`,
  ];
  pushProse(out, t.description);
  pushAiNotes(out, t.aiDescription);
  pushPolicies(out, t.policy ?? []);
  out.push(renderColumnsTable(t.columns, t.relations));
  pushColumnNotes(out, t.columns);
  pushSecurity(out, t.privileges);
  pushRowSecurity(out, t.rowSecurity);
  return out.join('\n\n');
}

function renderView(v: ViewContext, examples: { description: string; sql: string }[]): string {
  const out: string[] = [
    `<a id="${viewAnchor(v)}"></a>`,
    `### ${escapeInline(v.label)} (${code(v.qualifiedName)})`,
  ];
  pushProse(out, v.description);
  pushAiNotes(out, v.aiDescription);
  pushPolicies(out, v.policy ?? []);
  if (v.underlyingTables.length > 0) {
    const tables = v.underlyingTables.map((u) => code(`${u.schema}.${u.name}`)).join(', ');
    out.push(`**Underlying tables:** ${tables}`);
  }
  out.push(renderColumnsTable(v.columns, []));
  pushColumnNotes(out, v.columns);
  pushSecurity(out, v.privileges);
  for (const ex of examples) {
    out.push(`**Example query — ${escapeInline(ex.description)}**`);
    out.push(fencedSql(ex.sql));
  }
  out.push('**Definition**');
  out.push(fencedSql(v.rawView.definition));
  return out.join('\n\n');
}

function renderEnum(e: EnumContext): string {
  const out: string[] = [
    `<a id="${enumAnchor(e)}"></a>`,
    `### ${code(`${e.schema}.${e.name}`)}`,
  ];
  out.push(e.values.map((val) => `- ${code(val)}`).join('\n'));
  return out.join('\n\n');
}

function renderColumnsTable(columns: ColumnContext[], relations: RelationContext[]): string {
  // Map each FK column to its positionally-aligned referenced column. A
  // composite FK contributes every member column (not just the first), so the
  // Markdown agrees with the API / MCP relation metadata.
  const fkRefByColumn = new Map<string, { schema: string; table: string; column: string }>();
  for (const rel of relations) {
    const fields = rel.fields ?? [rel.field];
    const refCols = rel.references.columns ?? [rel.references.column];
    fields.forEach((field, i) => {
      fkRefByColumn.set(field, {
        schema: rel.references.schema,
        table: rel.references.table,
        column: refCols[i]!,
      });
    });
  }

  const header = '| Column | Type | Null | Default | Key | Description |';
  const divider = '| --- | --- | --- | --- | --- | --- |';
  const rows = columns.map((c) => {
    const key = columnKey(c, fkRefByColumn.get(c.name));
    const def = c.defaultExpr ? code(c.defaultExpr) : '';
    const desc = columnDescription(c);
    return `| ${code(c.name)} | ${escapeCell(c.dataType)} | ${c.nullable ? 'yes' : 'no'} | ${def} | ${key} | ${desc} |`;
  });
  return [header, divider, ...rows].join('\n');
}

function columnKey(
  column: ColumnContext,
  ref: { schema: string; table: string; column: string } | undefined,
): string {
  const parts: string[] = [];
  if (column.isPrimaryKey) parts.push('PK');
  if (ref) {
    parts.push(`FK → ${escapeCell(`${ref.schema}.${ref.table}.${ref.column}`)}`);
  } else if (column.isForeignKey) {
    parts.push('FK');
  }
  return parts.join(', ');
}

/** A one-line, table-cell-safe description: cleaned of tag lines, with the
 *  enum domain appended when present. */
function columnDescription(column: ColumnContext): string {
  const prose = cleanProse(column.description);
  const parts: string[] = [];
  if (prose) parts.push(escapeCell(prose));
  if (column.enumValues && column.enumValues.length > 0) {
    parts.push(`One of: ${column.enumValues.map(code).join(', ')}.`);
  }
  return parts.join(' ');
}

function pushProse(out: string[], description: string | null): void {
  const prose = cleanProse(description);
  if (prose) out.push(prose);
}

function pushAiNotes(out: string[], aiDescription: string | null): void {
  if (!aiDescription) return;
  const quoted = aiDescription
    .split('\n')
    .map((line) => `> ${line}`)
    .join('\n');
  out.push(`**AI notes:**\n\n${quoted}`);
}

/** Collapse a multi-line note to a single line for a list item. */
function oneLine(text: string): string {
  return text
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l.length > 0)
    .join(' ');
}

/** Per-column `@ai:` / `@policy:` notes. The columns table only carries the
 *  plain-prose description (and enum domain); the advisory notes that drive an
 *  AI agent — "do not use this column", "value at the captured price" — live
 *  here so the human-readable doc surfaces the same guidance MCP does. */
function pushColumnNotes(out: string[], columns: ColumnContext[]): void {
  const items: string[] = [];
  for (const c of columns) {
    const parts: string[] = [];
    if (c.aiDescription) parts.push(`*AI:* ${escapeInline(oneLine(c.aiDescription))}`);
    if (c.policy && c.policy.length > 0) {
      parts.push(`*Policy:* ${c.policy.map((p) => escapeInline(oneLine(p))).join(' ')}`);
    }
    if (parts.length > 0) items.push(`- ${code(c.name)} — ${parts.join(' ')}`);
  }
  if (items.length > 0) out.push(`**Column notes:**\n\n${items.join('\n')}`);
}

/** Privilege-aware mode (issue #99): the effective GRANTs of the evaluated role
 *  on this relation, so a reader knows what it may touch. Advisory only —
 *  PostgreSQL (GRANTs + RLS) enforces access. Omitted in schema-wide mode. */
function pushSecurity(out: string[], privileges: RelationPrivileges | undefined): void {
  if (!privileges) return;
  const yn = (b: boolean): string => (b ? 'yes' : 'no');
  out.push(
    `**Security** — effective privileges for role ${code(privileges.role)} ` +
      `(advisory; PostgreSQL enforces access):\n\n` +
      '| SELECT | INSERT | UPDATE | DELETE |\n' +
      '| --- | --- | --- | --- |\n' +
      `| ${yn(privileges.select)} | ${yn(privileges.insert)} | ` +
      `${yn(privileges.update)} | ${yn(privileges.delete)} |`,
  );
}

/** Row-level security signal: tell a reader the table's rows
 *  are filtered by policy, so the schema is not the whole story for who sees
 *  what. Surfaced on tables only, and only when RLS is enabled (a non-RLS table
 *  needs no caveat). The policy expressions are never read or shown. */
function pushRowSecurity(out: string[], rls: RowSecurity | undefined): void {
  if (!rls?.enabled) return;
  const detail = rls.hasPolicies
    ? 'rows are filtered by policy for the connecting role, and writes may be rejected'
    : 'no policy is defined, so non-owner roles can read and write no rows (default-deny)';
  const forced = rls.forced
    ? ' Also applies to the table owner (roles with BYPASSRLS still bypass it).'
    : '';
  // Only where a policy exists: the no-policy branch above already says every
  // command is refused.
  const denied = rls.deniedCommands ?? [];
  const perCommand =
    rls.hasPolicies && denied.length > 0
      ? ` No permissive policy covers ${denied.join(', ')}, so ` +
        `${denied.length === 1 ? 'that command is' : 'those commands are'} refused for every ` +
        'role RLS applies to, whatever privileges have been granted. An INSERT raises an error ' +
        'only once it writes a row, and one that writes none reports success; a refused SELECT, ' +
        'UPDATE or DELETE matches no rows instead of failing.'
      : '';
  out.push(
    `**Row-level security** — enabled (advisory; PostgreSQL enforces access): ` +
      `${detail}.${perCommand}${forced}`,
  );
}

function pushPolicies(out: string[], policies: string[]): void {
  if (policies.length === 0) return;
  const list = policies.map((p) => `- ${escapeInline(p)}`).join('\n');
  out.push(`**Policies:**\n\n${list}`);
}

/** Drop `@ai:` / `@policy:` / other tag lines from a COMMENT body, leaving the
 *  human prose. Tag lines are surfaced separately as structured sections. */
function cleanProse(description: string | null): string | null {
  if (description === null) return null;
  const kept = description.split('\n').filter((line) => !line.trim().startsWith('@'));
  const text = kept.join('\n').trim();
  return text === '' ? null : text;
}

function fencedSql(sql: string): string {
  return ['```sql', sql.trim(), '```'].join('\n');
}

function code(value: string): string {
  return `\`${value}\``;
}

/** Escape a value for inline Markdown text (outside a table cell). */
function escapeInline(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}

/** Collapse whitespace and escape a value so it is safe inside a Markdown
 *  table cell. The backslash is escaped first so a pre-existing `\` cannot
 *  swallow the escape we add for the pipe. All regexes are linear (single,
 *  unanchored) — no ReDoS. */
function escapeCell(value: string): string {
  return value
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\\/g, '\\\\')
    .replace(/\|/g, '\\|');
}

/** Collapse a value to a Mermaid identifier (entity id / attribute name):
 *  keep `[A-Za-z0-9_]`, replace every other run with `_`. Mermaid expects a
 *  token to begin with a letter, so a value that would start with a digit or
 *  underscore (or sanitize to empty) is prefixed with `x`. The precise name
 *  stays verbatim in the columns table below the diagram. Single, linear
 *  regexes — no ReDoS. */
function mermaidIdent(value: string): string {
  const v = value.replace(/[^A-Za-z0-9_]+/g, '_');
  return /^[A-Za-z]/.test(v) ? v : `x${v}`;
}

/** A Mermaid-safe attribute type token. A Mermaid attribute type must be a
 *  single word that begins with a letter, so a SQL type with spaces or
 *  punctuation ("timestamp with time zone", "numeric(12,2)") is folded to
 *  underscores and prefixed if it would not start with a letter. The precise
 *  type is kept verbatim in the columns table below the diagram. */
function mermaidType(dataType: string): string {
  const t = dataType
    .trim()
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/^_+/, '')
    .replace(/_+$/, '');
  if (t === '') return 'unknown';
  return /^[A-Za-z]/.test(t) ? t : `t_${t}`;
}

/** Trim to a single-line excerpt, with an ellipsis when truncated. */
function truncate(text: string, max = 160): string {
  return text.length <= max ? text : `${text.slice(0, max - 1).trimEnd()}…`;
}

function tableAnchor(t: TableContext): string {
  return `table-${slug(t.qualifiedName)}`;
}

function viewAnchor(v: ViewContext): string {
  return `view-${slug(v.qualifiedName)}`;
}

function enumAnchor(e: EnumContext): string {
  return `enum-${slug(`${e.schema}.${e.name}`)}`;
}

/** A deterministic, renderer-independent anchor slug. Paired with an explicit
 *  `<a id>` so the table-of-contents links resolve regardless of how a given
 *  Markdown renderer auto-slugs headings. */
function slug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+/, '')
    .replace(/-+$/, '');
}
