// OpenAPI 3.1 document generation from a SchemaContext (Kozou v0.2 spec
// §3.2). The differentiator over a generic auto-API is that COMMENT-derived
// metadata is baked into the document: table/view/column descriptions, the
// `@ai:` notes (as `x-kozou-ai`), CHECK / ENUM members (as `enum`), and the
// resolved widget (as `x-kozou-widget`).
//
// Pure function — no I/O. The server builds the document once at start and
// serves it at `GET /openapi.json`.

import type {
  SchemaContext,
  TableContext,
  ViewContext,
  ColumnContext,
  RelationContext,
  WidgetType,
} from '@kozou/core';

export type OpenApiOptions = {
  title?: string;
  version?: string;
};

type JsonObject = Record<string, unknown>;

/** A table or a view — both expose the fields the document needs. */
type ResourceLike = TableContext | ViewContext;

export function buildOpenApiDocument(
  schema: SchemaContext,
  opts: OpenApiOptions = {},
): JsonObject {
  const resources: { resource: ResourceLike; writable: boolean }[] = [
    ...schema.tables.map((t) => ({ resource: t, writable: true })),
    ...schema.views.map((v) => ({ resource: v, writable: false })),
  ];

  // Use the bare name as the URL segment when it is unique across schemas,
  // otherwise the qualified name — mirroring the request resolver.
  const nameCounts = new Map<string, number>();
  for (const { resource } of resources) {
    nameCounts.set(resource.name, (nameCounts.get(resource.name) ?? 0) + 1);
  }
  const segmentFor = (r: ResourceLike): string =>
    nameCounts.get(r.name) === 1 ? r.name : r.qualifiedName;

  const knownQNames = new Set(resources.map(({ resource }) => resource.qualifiedName));

  const paths: JsonObject = {};
  const schemas: JsonObject = {};

  for (const { resource, writable } of resources) {
    const ref = `#/components/schemas/${resource.qualifiedName}`;
    const relations: RelationContext[] = 'relations' in resource ? resource.relations : [];
    schemas[resource.qualifiedName] = resourceSchema(resource, relations, knownQNames);
    Object.assign(paths, resourcePaths(resource, segmentFor(resource), ref, writable));
  }

  return {
    openapi: '3.1.0',
    info: {
      title: opts.title ?? 'Kozou API',
      version: opts.version ?? '0.0.0',
      description:
        'REST API generated by Kozou from PostgreSQL DDL + COMMENT. Descriptions, enums, and AI notes below are sourced from the database COMMENTs.',
    },
    paths,
    components: { schemas },
  };
}

function resourceSchema(
  resource: ResourceLike,
  relations: RelationContext[],
  knownQNames: Set<string>,
): JsonObject {
  const properties: JsonObject = {};
  const required: string[] = [];
  for (const column of resource.columns) {
    properties[column.name] = columnSchema(column);
    if (!column.nullable) required.push(column.name);
  }

  const schema: JsonObject = { type: 'object', properties };
  if (resource.description) schema.description = resource.description;
  if (resource.aiDescription) schema['x-kozou-ai'] = resource.aiDescription;
  if (required.length > 0) schema.required = required;

  // Embeddable forward relations, as a hint for clients building `?embed=`.
  // Only relations whose target is itself an exposed resource are listed.
  const embeds = embedHints(relations, knownQNames);
  if (embeds.length > 0) schema['x-kozou-embeds'] = embeds;
  return schema;
}

function embedHints(relations: RelationContext[], knownQNames: Set<string>): JsonObject[] {
  const hints: JsonObject[] = [];
  for (const r of relations) {
    const qn = `${r.references.schema}.${r.references.table}`;
    if (!knownQNames.has(qn)) continue;
    hints.push({ field: r.field, key: r.references.table, target: `#/components/schemas/${qn}` });
  }
  return hints;
}

function columnSchema(column: ColumnContext): JsonObject {
  const base = widgetType(column.widget);
  const schema: JsonObject = { ...base };

  if (column.nullable && typeof schema.type === 'string') {
    schema.type = [schema.type, 'null'];
  }
  if (column.enumValues && column.enumValues.length > 0) {
    schema.enum = column.nullable ? [...column.enumValues, null] : [...column.enumValues];
  }
  if (column.description) schema.description = column.description;
  if (column.aiDescription) schema['x-kozou-ai'] = column.aiDescription;
  schema['x-kozou-widget'] = column.widget;
  return schema;
}

function widgetType(widget: WidgetType): JsonObject {
  switch (widget) {
    case 'number':
    case 'currency':
      return { type: 'number' };
    case 'boolean':
      return { type: 'boolean' };
    case 'date':
      return { type: 'string', format: 'date' };
    case 'datetime':
      return { type: 'string', format: 'date-time' };
    case 'uuid':
      return { type: 'string', format: 'uuid' };
    case 'image-url':
      return { type: 'string', format: 'uri' };
    case 'json':
      return { type: 'object' };
    case 'text':
    case 'textarea':
    case 'enum-select':
    case 'relation-select':
    default:
      return { type: 'string' };
  }
}

function resourcePaths(
  resource: ResourceLike,
  segment: string,
  ref: string,
  writable: boolean,
): JsonObject {
  const rowRef = { $ref: ref };
  const label = resource.label || resource.name;

  const collection: JsonObject = {
    get: {
      summary: `List ${label}`,
      description: resource.description ?? undefined,
      parameters: [...listParameters(), embedParam()],
      responses: {
        '200': jsonResponse(`A page of ${label}.`, listResultSchema(rowRef)),
      },
    },
  };
  if (writable) {
    collection.post = {
      summary: `Create a ${label} row`,
      requestBody: jsonBody(rowRef),
      responses: {
        '201': jsonResponse('The created row.', rowRef),
        '400': errorResponse('Validation error.'),
      },
    };
  }

  const idParam = {
    name: 'id',
    in: 'path',
    required: true,
    schema: { type: 'string' },
    description: 'Primary key of the row.',
  };
  const item: JsonObject = {
    get: {
      summary: `Fetch a ${label} row by id`,
      parameters: [idParam, embedParam()],
      responses: {
        '200': jsonResponse('The row.', rowRef),
        '404': errorResponse('No such row.'),
      },
    },
  };
  if (writable) {
    item.patch = {
      summary: `Update a ${label} row`,
      parameters: [idParam],
      requestBody: jsonBody(rowRef),
      responses: {
        '200': jsonResponse('The updated row.', rowRef),
        '404': errorResponse('No such row.'),
      },
    };
    item.delete = {
      summary: `Delete a ${label} row`,
      parameters: [idParam],
      responses: {
        '200': jsonResponse('The deleted row.', rowRef),
        '404': errorResponse('No such row.'),
      },
    };
  }

  return {
    [`/${segment}`]: collection,
    [`/${segment}/{id}`]: item,
  };
}

function listParameters(): JsonObject[] {
  return [
    queryParam('page', { type: 'integer', minimum: 1 }, '1-based page index.'),
    queryParam('pageSize', { type: 'integer', minimum: 1 }, 'Rows per page.'),
    queryParam('sort', { type: 'string' }, 'Comma-separated `field.asc` / `field.desc`.'),
    queryParam('search', { type: 'string' }, 'Free-text ILIKE across text columns.'),
  ];
}

function queryParam(name: string, schema: JsonObject, description: string): JsonObject {
  return { name, in: 'query', required: false, schema, description };
}

function embedParam(): JsonObject {
  return queryParam(
    'embed',
    { type: 'string' },
    'Comma-separated forward to-one relations to inline as nested objects; dot for depth (e.g. "author,editions.books.authors"). Each segment is a foreign-key column name or its referenced table name.',
  );
}

function listResultSchema(rowRef: JsonObject): JsonObject {
  return {
    type: 'object',
    properties: {
      rows: { type: 'array', items: rowRef },
      total: { type: 'integer' },
      page: { type: 'integer' },
      pageSize: { type: 'integer' },
    },
    required: ['rows', 'total', 'page', 'pageSize'],
  };
}

function jsonResponse(description: string, schema: JsonObject): JsonObject {
  return { description, content: { 'application/json': { schema } } };
}

function jsonBody(schema: JsonObject): JsonObject {
  return { required: true, content: { 'application/json': { schema } } };
}

function errorResponse(description: string): JsonObject {
  return jsonResponse(description, {
    type: 'object',
    properties: {
      error: {
        type: 'object',
        properties: { code: { type: 'string' }, message: { type: 'string' } },
      },
    },
  });
}
