// OpenAPI 3.1 document generation from a SchemaContext.
// The differentiator over a generic auto-API is that COMMENT-derived
// metadata is baked into the document: table/view/column descriptions, the
// `@ai:` notes (as `x-kozou-ai`), `@policy:` rules (as `x-kozou-policy`),
// CHECK / ENUM members (as `enum`), and the resolved widget (as
// `x-kozou-widget`).
//
// `@policy:` rules are advisory metadata for AI agents and clients; they are
// not enforced here. Hard access control is the schema author's Postgres
// row-level security (see auth.ts).
//
// Pure function — no I/O. The server builds the document once at start and
// serves it at `GET /openapi.json`.

import type {
  SchemaContext,
  TableContext,
  ViewContext,
  ColumnContext,
  RelationContext,
  WidgetType,
  FunctionContext,
  FunctionArgContext,
  FunctionReturnContext,
} from '@kozou/core';
import { RESERVED_PARAMS } from './handler.js';

export type OpenApiOptions = {
  title?: string;
  version?: string;
};

type JsonObject = Record<string, unknown>;

/** A table or a view — both expose the fields the document needs. */
type ResourceLike = TableContext | ViewContext;

export function buildOpenApiDocument(
  schema: SchemaContext,
  opts: OpenApiOptions = {},
): JsonObject {
  const resources: { resource: ResourceLike; writable: boolean }[] = [
    ...schema.tables.map((t) => ({ resource: t, writable: true })),
    ...schema.views.map((v) => ({ resource: v, writable: false })),
  ];

  // Use the bare name as the URL segment when it is unique across schemas,
  // otherwise the qualified name — mirroring the request resolver.
  const nameCounts = new Map<string, number>();
  for (const { resource } of resources) {
    nameCounts.set(resource.name, (nameCounts.get(resource.name) ?? 0) + 1);
  }
  const segmentFor = (r: ResourceLike): string =>
    nameCounts.get(r.name) === 1 ? r.name : r.qualifiedName;

  const knownQNames = new Set(resources.map(({ resource }) => resource.qualifiedName));

  // Reverse index for one-to-many embed hints: parent qualifiedName -> children.
  const reverseByParent = new Map<string, ReverseEntry[]>();
  for (const t of schema.tables) {
    for (const rel of t.relations ?? []) {
      const parentQN = `${rel.references.schema}.${rel.references.table}`;
      const entry: ReverseEntry = {
        childName: t.name,
        childQN: t.qualifiedName,
        field: rel.field,
        fields: rel.fields ?? [rel.field],
      };
      const list = reverseByParent.get(parentQN);
      if (list) list.push(entry);
      else reverseByParent.set(parentQN, [entry]);
    }
  }

  const paths: JsonObject = {};
  const schemas: JsonObject = {};

  for (const { resource, writable } of resources) {
    const qn = resource.qualifiedName;
    const ref = `#/components/schemas/${qn}`;
    const relations: RelationContext[] = 'relations' in resource ? resource.relations : [];
    const reverse = reverseByParent.get(qn) ?? [];
    const parentColumns = new Set(resource.columns.map((c) => c.name));
    const embeds = embedHints(relations, reverse, knownQNames, parentColumns);
    schemas[qn] = resourceSchema(resource, embeds);

    // Request-body schemas are distinct from the response row schema: a create
    // input does not require columns the database can supply, and a partial
    // update requires nothing (see requestInputSchema).
    let createRef: string | undefined;
    let updateRef: string | undefined;
    if (writable) {
      const createName = `${qn}.CreateInput`;
      schemas[createName] = requestInputSchema(resource, 'create');
      createRef = `#/components/schemas/${createName}`;
      const pk = 'primaryKey' in resource ? resource.primaryKey : [];
      if (pk.length >= 1) {
        const updateName = `${qn}.UpdateInput`;
        schemas[updateName] = requestInputSchema(resource, 'update');
        updateRef = `#/components/schemas/${updateName}`;
      }
    }

    Object.assign(
      paths,
      resourcePaths(resource, segmentFor(resource), ref, writable, embeds.length > 0, {
        create: createRef,
        update: updateRef,
      }),
    );
  }

  // RPC operations (issue #103): one `POST /rpc/<schema>.<fn>` per exposed
  // function, addressed by its schema-qualified identity. COMMENT-derived
  // metadata (@ai / @policy) rides along as x-kozou-* the same way it does for
  // tables/views.
  for (const fn of schema.functions ?? []) {
    Object.assign(paths, rpcPaths(fn));
  }

  return {
    openapi: '3.1.0',
    info: {
      title: opts.title ?? 'Kozou API',
      version: opts.version ?? '0.0.0',
      description:
        'REST API generated by Kozou from PostgreSQL DDL + COMMENT. Descriptions, enums, and AI notes below are sourced from the database COMMENTs.',
    },
    paths,
    components: { schemas },
  };
}

function resourceSchema(resource: ResourceLike, embeds: JsonObject[]): JsonObject {
  const properties: JsonObject = {};
  const required: string[] = [];
  for (const column of resource.columns) {
    properties[column.name] = columnSchema(column);
    if (!column.nullable) required.push(column.name);
  }

  const schema: JsonObject = { type: 'object', properties };
  if (resource.description) schema.description = resource.description;
  if (resource.aiDescription) schema['x-kozou-ai'] = resource.aiDescription;
  if (resource.policy && resource.policy.length > 0) schema['x-kozou-policy'] = resource.policy;
  if (required.length > 0) schema.required = required;

  // Embeddable relations (forward to-one + reverse to-many, only targets that
  // are themselves exposed resources), as a hint for clients building
  // `?embed=`. Computed once by the caller and shared with the path builder so
  // the `embed` query parameter is only advertised where it is usable.
  if (embeds.length > 0) schema['x-kozou-embeds'] = embeds;
  return schema;
}

/** The request-body schema for `POST` (`create`) or `PATCH` (`update`).
 *  Distinct from the response row schema because the contract differs:
 *  - `create`: only columns that are NOT NULL *and* have no database default
 *    are required (the rest the server / PostgreSQL can supply); an empty body
 *    is valid when nothing is required.
 *  - `update`: a partial — any subset of columns, so no row-level `required`,
 *    but at least one column (the runtime rejects an empty update with 400),
 *    modelled as `minProperties: 1`.
 *  Both reject unknown columns at runtime (400), modelled as
 *  `additionalProperties: false`. */
function requestInputSchema(resource: ResourceLike, kind: 'create' | 'update'): JsonObject {
  const label = resource.label || resource.name;
  const properties: JsonObject = {};
  const required: string[] = [];
  for (const column of resource.columns) {
    properties[column.name] = columnSchema(column);
    if (kind === 'create' && !column.nullable && column.defaultExpr === null) {
      required.push(column.name);
    }
  }

  const schema: JsonObject = { type: 'object', properties, additionalProperties: false };
  if (kind === 'create') {
    schema.description = `Create input for ${label}. Columns with a database default or a server-generated value may be omitted.`;
    if (required.length > 0) schema.required = required;
  } else {
    schema.description = `Partial update for ${label}. Supply at least one of the columns to change.`;
    schema.minProperties = 1;
  }
  return schema;
}

type ReverseEntry = { childName: string; childQN: string; field: string; fields: string[] };

/** Embeddable-relation hints, derived with the same semantics as the runtime
 *  embed resolver (embed.ts) so the document never advertises a relation the
 *  request handler would reject:
 *
 *  - A forward (to-one) relation is selectable by its FK column name, so it is
 *    always embeddable (even when several FKs point at the same table).
 *  - A reverse (to-many) relation is selectable only by the child table name,
 *    and only when that child has exactly one FK back to this parent; multiple
 *    reverse FKs from one child are not yet resolvable (a 400 at runtime), so
 *    they are dropped here.
 *  - The result `key` is chosen the way embed.ts's `chooseKey` does — the
 *    target table name, then the FK field with a trailing id-suffix stripped,
 *    then the raw FK field — skipping any candidate that collides with a parent
 *    column or a key already assigned to an earlier hint. (The raw field is a
 *    parent column for a forward relation, so it only ever helps a reverse one,
 *    whose FK lives on the child.) A relation with no usable key (every
 *    candidate collides) would 400 at runtime, so it is dropped too.
 *
 *  `key` reflects the assignment when the whole advertised set is embedded
 *  together; embedding a subset may yield a simpler key, but `field` (forward)
 *  / the target table name (reverse) is always a valid `?embed=` selector. */
function embedHints(
  forward: RelationContext[],
  reverse: ReverseEntry[],
  knownQNames: Set<string>,
  parentColumns: Set<string>,
): JsonObject[] {
  const hints: JsonObject[] = [];
  const taken = new Set<string>();

  // Table names reachable as a forward selector — a reverse embed by child
  // table name is shadowed by (and so unreachable behind) a forward to the same
  // table, since matchForward is tried first (embed.ts). Used to avoid
  // advertising an unreachable reverse below.
  const forwardTables = new Set(forward.map((r) => r.references.table));

  for (const r of forward) {
    const qn = `${r.references.schema}.${r.references.table}`;
    if (!knownQNames.has(qn)) continue;
    const fields = r.fields ?? [r.field];
    // A composite FK has no single-column selector, so it is reachable only by
    // its (unique) referenced table name; if another FK also targets that table
    // the table-name selector is ambiguous and the composite relation is
    // unreachable at runtime, so it is dropped here (matchForward in embed.ts).
    if (fields.length > 1 && forward.filter((x) => x.references.table === r.references.table).length > 1) {
      continue;
    }
    const key = pickEmbedKey([r.references.table, stripIdSuffix(r.field), r.field], taken, parentColumns);
    if (key === undefined) continue;
    taken.add(key);
    const hint: JsonObject = { field: r.field, key, target: `#/components/schemas/${qn}`, cardinality: 'to-one' };
    // Composite FKs carry the full column set (the scalar `field` stays `[0]`).
    if (fields.length > 1) hint.fields = [...fields];
    hints.push(hint);
  }

  // Group reverse entries by child table name; a child with more than one FK
  // back to this parent is ambiguous (unreachable) and dropped.
  const byChild = new Map<string, ReverseEntry[]>();
  for (const e of reverse) {
    const list = byChild.get(e.childName);
    if (list) list.push(e);
    else byChild.set(e.childName, [e]);
  }
  for (const entries of byChild.values()) {
    if (entries.length !== 1) continue;
    const e = entries[0];
    if (!knownQNames.has(e.childQN)) continue;
    // A reverse embed is selected by the child table name. If a forward
    // relation targets a table of that same name, matchForward (tried first)
    // shadows the reverse, so it is unreachable — do not advertise it.
    if (forwardTables.has(e.childName)) continue;
    const key = pickEmbedKey([e.childName, stripIdSuffix(e.field), e.field], taken, parentColumns);
    if (key === undefined) continue;
    taken.add(key);
    const hint: JsonObject = {
      field: e.field,
      key,
      target: `#/components/schemas/${e.childQN}`,
      cardinality: 'to-many',
    };
    if (e.fields.length > 1) hint.fields = [...e.fields];
    hints.push(hint);
  }

  return hints;
}

/** First candidate key that is non-empty and collides with neither a parent
 *  column nor an already-assigned key. Mirrors embed.ts `chooseKey`. */
function pickEmbedKey(
  candidates: string[],
  taken: Set<string>,
  parentColumns: Set<string>,
): string | undefined {
  for (const key of candidates) {
    if (key.length > 0 && !taken.has(key) && !parentColumns.has(key)) return key;
  }
  return undefined;
}

function stripIdSuffix(field: string): string {
  const stripped = field.replace(/_(id|uuid|fk|key)$/i, '');
  return stripped.length > 0 ? stripped : field;
}

function columnSchema(column: ColumnContext): JsonObject {
  const base = widgetType(column.widget);
  const schema: JsonObject = { ...base };

  if (column.nullable && typeof schema.type === 'string') {
    schema.type = [schema.type, 'null'];
  }
  if (column.enumValues && column.enumValues.length > 0) {
    schema.enum = column.nullable ? [...column.enumValues, null] : [...column.enumValues];
  }
  if (column.description) schema.description = column.description;
  if (column.aiDescription) schema['x-kozou-ai'] = column.aiDescription;
  if (column.policy && column.policy.length > 0) schema['x-kozou-policy'] = column.policy;
  schema['x-kozou-widget'] = column.widget;
  return schema;
}

function widgetType(widget: WidgetType): JsonObject {
  switch (widget) {
    case 'number':
    case 'currency':
      return { type: 'number' };
    case 'boolean':
      return { type: 'boolean' };
    case 'date':
      return { type: 'string', format: 'date' };
    case 'datetime':
      return { type: 'string', format: 'date-time' };
    case 'uuid':
      return { type: 'string', format: 'uuid' };
    case 'image-url':
      return { type: 'string', format: 'uri' };
    case 'json':
      return { type: 'object' };
    case 'text':
    case 'textarea':
    case 'enum-select':
    case 'relation-select':
    default:
      return { type: 'string' };
  }
}

function resourcePaths(
  resource: ResourceLike,
  segment: string,
  ref: string,
  writable: boolean,
  hasEmbeds: boolean,
  requestRefs: { create?: string; update?: string },
): JsonObject {
  const rowRef = { $ref: ref };
  const label = resource.label || resource.name;
  const primaryKey = 'primaryKey' in resource ? resource.primaryKey : [];
  // The relation-select (`as=options`) mode builds its option `id` from the
  // primary key (a scalar for a single-column key, an array of components for
  // a composite key); the handler rejects a key-less resource (a view, or a
  // table without a primary key) with 400. Only advertise the mode where it
  // actually works.
  const hasOptions = primaryKey.length >= 1;

  // The `embed` parameter is only advertised where the resource has at least
  // one embeddable relation; a non-empty `embed` on a relation-less resource
  // (e.g. a view) is rejected with 400, so listing it would be misleading.
  const embedParams = hasEmbeds ? [embedParam()] : [];

  // List/filter/embed parameters first; relation-select controls are folded in
  // afterwards. A column named like an options control (`as`, `label`, ...)
  // would collide, so rather than emit a duplicate (invalid) or silently drop
  // the control, merge its meaning into the colliding filter's description.
  const collectionParams: JsonObject[] = [
    ...listParameters(),
    ...filterParameters(resource),
    ...embedParams,
  ];
  if (hasOptions) {
    for (const control of optionsParameters()) {
      const clash = collectionParams.find((p) => p.name === control.name);
      if (clash) {
        clash.description = `${clash.description ?? ''} In \`as=options\` mode this parameter is the relation-select control instead — ${control.description as string}`;
      } else {
        collectionParams.push(control);
      }
    }
  }

  // Database-mapped error statuses (the request handler's SQLSTATE mapping):
  // privilege / row-level-security denials surface as 403 on every
  // data-touching operation; constraint conflicts as 409 on writes.
  const forbiddenResp = (): JsonObject =>
    errorResponse('Permission denied (database privilege or row-level security).');
  const conflictResp = (): JsonObject =>
    errorResponse('Constraint conflict (unique or foreign-key violation).');

  const collection: JsonObject = {
    get: {
      summary: `List ${label}`,
      description: resource.description ?? undefined,
      parameters: collectionParams,
      responses: {
        '200': hasOptions
          ? jsonResponse(
              `A page of ${label}; or relation-select options when \`as=options\`.`,
              { oneOf: [listResultSchema(rowRef), optionsResultSchema(primaryKey)] },
            )
          : jsonResponse(`A page of ${label}.`, listResultSchema(rowRef)),
        '403': forbiddenResp(),
      },
    },
  };
  if (writable) {
    collection.post = {
      summary: `Create a ${label} row`,
      requestBody: jsonBody(requestRefs.create ? { $ref: requestRefs.create } : rowRef),
      responses: {
        '201': jsonResponse('The created row.', rowRef),
        '400': errorResponse('Validation error.'),
        '403': forbiddenResp(),
        '409': conflictResp(),
      },
    };
  }

  const paths: JsonObject = { [`/${segment}`]: collection };

  // Item-by-id routes only exist for resources addressable by a primary key.
  // Views and primary-key-less tables cannot be fetched/updated/deleted by id
  // (the request handler rejects such reads with 400), so the document must
  // not advertise an item path for them.
  if (primaryKey.length >= 1) {
    const idParam = itemIdParam(resource);
    const item: JsonObject = {
      get: {
        summary: `Fetch a ${label} row by id`,
        parameters: [idParam, ...embedParams],
        responses: {
          '200': jsonResponse('The row.', rowRef),
          '403': forbiddenResp(),
          '404': errorResponse('No such row.'),
        },
      },
    };
    if (writable) {
      item.patch = {
        summary: `Update a ${label} row`,
        parameters: [idParam],
        requestBody: jsonBody(requestRefs.update ? { $ref: requestRefs.update } : rowRef),
        responses: {
          '200': jsonResponse('The updated row.', rowRef),
          '400': errorResponse('Validation error.'),
          '403': forbiddenResp(),
          '404': errorResponse('No such row.'),
          '409': conflictResp(),
        },
      };
      item.delete = {
        summary: `Delete a ${label} row`,
        parameters: [idParam],
        responses: {
          '200': jsonResponse('The deleted row.', rowRef),
          '403': forbiddenResp(),
          '404': errorResponse('No such row.'),
          '409': conflictResp(),
        },
      };
    }
    paths[`/${segment}/{id}`] = item;
  }

  return paths;
}

/** The `{id}` path parameter. Only called for a resource with a non-empty
 *  primary key (the caller in `resourcePaths` guards on it). A composite
 *  primary key is addressed by comma-joining its components — in `primaryKey`
 *  declaration order — into the single `{id}` segment, each component
 *  percent-encoded. */
function itemIdParam(resource: ResourceLike): JsonObject {
  const pk = 'primaryKey' in resource ? resource.primaryKey : [];
  let description: string;
  if (pk.length > 1) {
    const cols = pk.map((c) => `\`${c}\``).join(', ');
    description =
      `Composite primary key: the components (${cols}) in this order, joined by an ` +
      `unescaped comma in the single path segment. Percent-encode reserved characters ` +
      `within a component; a component value cannot itself contain a comma (the segment ` +
      `is split on commas after URL-decoding).`;
  } else {
    description = `Primary key of the row (\`${pk[0]}\`).`;
  }
  return { name: 'id', in: 'path', required: true, schema: { type: 'string' }, description };
}

function listParameters(): JsonObject[] {
  return [
    queryParam('page', { type: 'integer', minimum: 1 }, '1-based page index.'),
    queryParam('pageSize', { type: 'integer', minimum: 1 }, 'Rows per page.'),
    queryParam('sort', { type: 'string' }, 'Comma-separated `field.asc` / `field.desc`.'),
    queryParam('search', { type: 'string' }, 'Free-text ILIKE across text columns.'),
  ];
}

/** Query parameters for the relation-select (`as=options`) mode of the
 *  collection `GET`. OpenAPI cannot express a response that depends on a query
 *  parameter value, so the alternate `{ options }` shape is offered as a
 *  `oneOf` on the same 200 and these controls are documented as optional. */
function optionsParameters(): JsonObject[] {
  return [
    queryParam(
      'as',
      { type: 'string', enum: ['options'] },
      'Set to `options` to switch this endpoint to relation-select mode: it returns `{ id, label }` pairs (see the alternate 200 schema) instead of full rows.',
    ),
    queryParam(
      'label',
      { type: 'string' },
      'Relation-select (`as=options`) only — required in that mode: the column whose value is each option\'s display `label`. It is not searched by `q` unless you also list it in `fields`.',
    ),
    queryParam(
      'fields',
      { type: 'string' },
      'Relation-select only: comma-separated columns that `q` is matched against. To search the label column, include it here.',
    ),
    queryParam(
      'q',
      { type: 'string' },
      'Relation-select only: free-text query, matched with ILIKE against the columns listed in `fields`. It has no effect when `fields` is empty.',
    ),
    queryParam(
      'limit',
      { type: 'integer', minimum: 1 },
      'Relation-select only: maximum number of options to return.',
    ),
  ];
}

/** Operators accepted by the `<column>=<op>.<value>` filter grammar. */
const FILTER_OPERATORS_DOC = 'eq, neq, gt, gte, lt, lte, like, ilike, in, is';

/** One query parameter per filterable column documenting the
 *  `<column>=<op>.<value>` grammar. Control keys (page/sort/…) are skipped so
 *  the doc never advertises them as filters. Multiple filters on one column
 *  combine with AND (e.g. a `gte`/`lte` range). */
function filterParameters(resource: ResourceLike): JsonObject[] {
  return resource.columns
    .filter((c) => !RESERVED_PARAMS.has(c.name))
    .map((c) =>
      queryParam(
        c.name,
        { type: 'string' },
        `Filter on \`${c.name}\`: \`<op>.<value>\` where op is one of ${FILTER_OPERATORS_DOC} ` +
          `(e.g. \`${c.name}=gte.10\`, \`${c.name}=in.(a,b)\`, \`${c.name}=is.null\`). ` +
          `A bare value means \`eq\`. Repeat the key to AND several conditions.`,
      ),
    );
}

function queryParam(name: string, schema: JsonObject, description: string): JsonObject {
  return { name, in: 'query', required: false, schema, description };
}

function embedParam(): JsonObject {
  return queryParam(
    'embed',
    { type: 'string' },
    'Comma-separated relations to inline in each row; use a dot for depth ' +
      '(e.g. "author,reviews.user"). A forward (to-one) relation — selected by ' +
      'its foreign-key column name or the referenced table name — is inlined as a ' +
      'nested object (or null). A reverse (to-many) relation — selected by the ' +
      'child table name, when that child has exactly one foreign key back — is ' +
      'inlined as an array. Each relation appears under the `key` shown in ' +
      '`x-kozou-embeds`; when several relations compete for a key (e.g. multiple ' +
      'foreign keys to one table), embedding only a subset may place one under a ' +
      'simpler key, so treat the selector — not the key — as the stable identifier.',
  );
}

function listResultSchema(rowRef: JsonObject): JsonObject {
  return {
    type: 'object',
    properties: {
      rows: { type: 'array', items: rowRef },
      total: { type: 'integer' },
      page: { type: 'integer' },
      pageSize: { type: 'integer' },
    },
    required: ['rows', 'total', 'page', 'pageSize'],
  };
}

/** The `as=options` response: `{ options: [{ id, label }] }`. A
 *  single-column key yields a scalar `id`; a composite key yields an array of
 *  key components in primary-key declaration order (a valid item id for the
 *  resource). */
function optionsResultSchema(primaryKey: string[]): JsonObject {
  const id: JsonObject =
    primaryKey.length > 1
      ? {
          type: 'array',
          items: { type: ['string', 'number'] },
          minItems: primaryKey.length,
          maxItems: primaryKey.length,
          description: `Composite key components, in declaration order: ${primaryKey.join(', ')}.`,
        }
      : { type: ['string', 'number'] };
  return {
    type: 'object',
    properties: {
      options: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            id,
            label: { type: 'string' },
          },
          required: ['id', 'label'],
        },
      },
    },
    required: ['options'],
  };
}

function jsonResponse(description: string, schema: JsonObject): JsonObject {
  return { description, content: { 'application/json': { schema } } };
}

function jsonBody(schema: JsonObject): JsonObject {
  return { required: true, content: { 'application/json': { schema } } };
}

function errorResponse(description: string): JsonObject {
  return jsonResponse(description, {
    type: 'object',
    properties: {
      error: {
        type: 'object',
        properties: { code: { type: 'string' }, message: { type: 'string' } },
      },
    },
  });
}

// ---- RPC (issue #103) ------------------------------------------------------

/** The `POST /rpc/<schema>.<fn>` operation for one exposed function. The path
 *  uses the schema-qualified identity; the request body is the named
 *  arguments; the response shape follows the v1 return mapping. */
function rpcPaths(fn: FunctionContext): JsonObject {
  const properties: JsonObject = {};
  const required: string[] = [];
  for (const arg of fn.args) {
    properties[arg.name] = argSchema(arg);
    if (!arg.hasDefault) required.push(arg.name);
  }
  const requestSchema: JsonObject = { type: 'object', properties, additionalProperties: false };
  if (required.length > 0) requestSchema.required = required;

  const operation: JsonObject = {
    operationId: `rpc.${fn.qualifiedName}`,
    summary: fn.label || fn.name,
    'x-kozou-volatility': fn.volatility,
    'x-kozou-security': fn.security,
    requestBody: {
      // A no-argument (or all-default) function accepts an empty body.
      required: required.length > 0,
      content: { 'application/json': { schema: requestSchema } },
    },
    responses: rpcResponses(fn.returns),
  };
  if (fn.description) operation.description = fn.description;
  if (fn.aiDescription) operation['x-kozou-ai'] = fn.aiDescription;
  if (fn.policy && fn.policy.length > 0) operation['x-kozou-policy'] = fn.policy;

  return { [`/rpc/${fn.qualifiedName}`]: { post: operation } };
}

/** JSON schema for one RPC argument, from its inferred widget + enum members,
 *  with the relation target (when hinted) surfaced as `x-kozou-relation`. */
function argSchema(arg: FunctionArgContext): JsonObject {
  const schema: JsonObject = { ...widgetType(arg.widget) };
  if (arg.enumValues && arg.enumValues.length > 0) schema.enum = [...arg.enumValues];
  schema['x-kozou-widget'] = arg.widget;
  schema['x-kozou-type'] = arg.typeName;
  if (arg.relation) {
    schema['x-kozou-relation'] = `${arg.relation.schema}.${arg.relation.table}.${arg.relation.column}`;
  }
  return schema;
}

/** Responses for an RPC operation: the success status/shape by return kind,
 *  plus the database-mapped 403 (no EXECUTE / RLS denial) and a 400 for
 *  a malformed body. */
function rpcResponses(returns: FunctionReturnContext): JsonObject {
  const base: JsonObject = {
    '400': errorResponse('Validation error (unknown or missing argument).'),
    '403': errorResponse('Permission denied (no EXECUTE privilege or row-level security).'),
    // A function that violates (or RAISEs with) a unique / foreign-key SQLSTATE
    // maps to 409 via the same classifier as table writes (#98 reuse).
    '409': errorResponse('Constraint conflict (unique or foreign-key violation).'),
  };
  if (returns.kind === 'void') {
    return { '204': { description: 'The function returned no value.' }, ...base };
  }
  return { '200': jsonResponse('The function result.', returnSchema(returns)), ...base };
}

/** Best-effort response schema for a return shape: a scalar is left
 *  unconstrained (the SQL type is advisory only, in `x-kozou-type`); a composite
 *  is an object of its columns; a SETOF is an array of objects (or of scalars
 *  when the row has no named columns). */
function returnSchema(returns: FunctionReturnContext): JsonObject {
  const objectOf = (columns: { name: string; typeName: string }[]): JsonObject => ({
    type: 'object',
    properties: Object.fromEntries(
      columns.map((c) => [c.name, { 'x-kozou-type': c.typeName }]),
    ),
  });
  switch (returns.kind) {
    case 'scalar':
      return { 'x-kozou-type': returns.typeName };
    case 'composite':
      return returns.columns ? objectOf(returns.columns) : { type: 'object' };
    case 'setof':
      return {
        type: 'array',
        items: returns.columns && returns.columns.length > 0 ? objectOf(returns.columns) : {},
      };
    default:
      return {};
  }
}
